[tox]
requires =
    tox-uv>=1.16
skipsdist = True

[testenv]
runner = uv-venv-lock-runner
uv_sync_locked = false
uv_sync_flags = --frozen
download = True
passenv =
    HOME
    AIRFLOW_HOME
    AWS_*
    BUILDKITE*
    CI_*
    DAGSTER_*
    DOCKER_*
    GOOGLE_*
    KUBECONFIG
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
dependency_groups =
    test
allowlist_externals =
  /bin/bash
  uv
commands =
  !windows: /bin/bash -c '! uv pip list --exclude-editable | grep -e dagster'
  default: pytest --log-cli-level=INFO --timeout=480 -m "mark_rabbitmq" -s -vv  -celery-k8s {posargs}
  markredis: pytest --log-cli-level=INFO --timeout=480 -m "mark_redis" -s -vv  -celery-k8s {posargs}
