# Regenerate the dbt manifest.json
dbt:
	dbt ls \
		--project-dir hacker_news_assets/activity_analytics/hacker_news_dbt \
		--profiles-dir hacker_news_assets/activity_analytics/hacker_news_dbt/config
