from typing import Any, NamedTuple, Optional

from dagster.core.definitions.events import AssetKey


class SourceAsset(NamedTuple):
    """A SourceAsset represents an asset that is not generated by any Dagster op."""

    key: AssetKey
    metadata: Optional[Any] = None
    io_manager_key: str = "io_manager"
