[tox]
requires =
    tox-uv>=1.16
skipsdist = true

[testenv]
runner = uv-venv-lock-runner
uv_sync_locked = false
uv_sync_flags = --frozen
download = True
passenv =
    CI_*
    POSTGRES_TEST_*
    BUILDKITE*
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
dependency_groups =
    test
    storage_tests_sqlalchemy_1_3: test-sqlalchemy-1-3
allowlist_externals =
  /bin/bash
  uv
commands =
  !windows: /bin/bash -c '! uv pip list --exclude-editable | grep -e dagster'
  storage_tests: pytest -vv {posargs}
  storage_tests_sqlalchemy_1_3: pytest -vv {posargs}
