[tox]
envlist = py312
skipsdist = True

[testenv]
download = True
install_command = uv pip install {opts} {packages}
passenv =
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
    CI_*
    BUILDKITE*
deps =
    -e ../buildkite-shared
    -e .
    pytest
    flaky
allowlist_externals =
  /bin/bash
  echo
  uv
commands =
  pytest -vv --durations 10 ./dagster_buildkite_tests {posargs}
