default_stages: [pre-commit] # don't run on push by default
repos:
- repo: local
  hooks:
  - id: ruff-format
    name: Ruff Format
    entry: ruff
    args: [format]
    language: system
    pass_filenames: false
  - id: ruff-lint
    name: Ruff Lint
    entry: ruff
    args: [check, --fix, --exit-non-zero-on-fix]
    language: system
    pass_filenames: false

  # We do not use ty's provided pre-commit hook because we need the environment management
  # supplied by `scripts/run-ty.py`.
  - id: ty
    name: ty
    entry: make quick_ty
    stages: [pre-push]
    # This means pre-commit will not try to install a new environment for this hook. It relies on
    # having a pre-existing `make` installed (and scripts/run-ty.py).
    language: system
    pass_filenames: false
    types: [python]
