[tox]
requires =
    tox-uv>=1.16
skipsdist = true

[testenv]
runner = uv-venv-lock-runner
uv_sync_locked = false
uv_sync_flags = --frozen
download = True
passenv =
    CI_*
    AWS_SECRET_ACCESS_KEY
    AWS_ACCESS_KEY_ID
    BUILDKITE*
    SNOWFLAKE_ACCOUNT
    SNOWFLAKE_USER
    SNOWFLAKE_DEMO_PRIVATE_KEY
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
extras =
    snowflake.sqlalchemy
dependency_groups =
    test
allowlist_externals =
  /bin/bash
  uv
commands =
  !windows: /bin/bash -c '! uv pip list --exclude-editable | grep -e dagster'
    pytest -vv {posargs}
