fragment IssueFields on Issue {
  publicId
  title
  description
  status
  context
  linkedObjects {
    ... on Run {
      __typename
      id
      status
      jobName
      startTime
      endTime
    }
    ... on Asset {
      __typename
      key {
        path
      }
    }
  }
  createdBy {
    ... on DagsterCloudUser {
      __typename
      displayName
      email
    }
    ... on ServiceUser {
      __typename
      displayName
      description
    }
  }
}

query GetIssue($issueId: String!) {
  issue(issueId: $issueId) {
    __typename
    ... on Issue {
      ...IssueFields
    }
    ... on UnauthorizedError {
      message
    }
    ... on PythonError {
      message
    }
  }
}

query ListIssues($limit: Int!, $cursor: String, $filters: IssuesFilter) {
  issues(limit: $limit, cursor: $cursor, filters: $filters) {
    __typename
    ... on IssueConnection {
      issues {
        ...IssueFields
      }
      cursor
      hasMore
    }
    ... on UnauthorizedError {
      message
    }
    ... on PythonError {
      message
    }
  }
}

mutation CreateIssue(
  $title: String!
  $description: String!
  $status: IssueStatus
  $origin: IssueLinkedObjectInput
) {
  createIssue(
    title: $title
    description: $description
    status: $status
    origin: $origin
  ) {
    __typename
    ... on CreateIssueSuccess {
      issue {
        ...IssueFields
      }
    }
    ... on UnauthorizedError {
      message
    }
    ... on PythonError {
      message
    }
  }
}

mutation UpdateIssue(
  $issueId: String!
  $status: IssueStatus
  $title: String
  $description: String
  $context: String
) {
  updateIssue(
    issueId: $issueId
    status: $status
    title: $title
    description: $description
    context: $context
  ) {
    __typename
    ... on UpdateIssueSuccess {
      issue {
        ...IssueFields
      }
    }
    ... on UnauthorizedError {
      message
    }
    ... on PythonError {
      message
    }
  }
}

mutation AddLinkToIssue(
  $issueId: String!
  $linkedObject: IssueLinkedObjectInput!
) {
  addLinkToIssue(issueId: $issueId, linkedObject: $linkedObject) {
    __typename
    ... on UpdateIssueSuccess {
      issue {
        ...IssueFields
      }
    }
    ... on UnauthorizedError {
      message
    }
    ... on PythonError {
      message
    }
  }
}

mutation RemoveLinkFromIssue(
  $issueId: String!
  $linkedObject: IssueLinkedObjectInput!
) {
  removeLinkFromIssue(issueId: $issueId, linkedObject: $linkedObject) {
    __typename
    ... on UpdateIssueSuccess {
      issue {
        ...IssueFields
      }
    }
    ... on UnauthorizedError {
      message
    }
    ... on PythonError {
      message
    }
  }
}
