query GetRun($runId: ID!) {
  runOrError(runId: $runId) {
    __typename
    ... on Run {
      runId
      status
      creationTime
      startTime
      endTime
      jobName
      runConfigYaml
      tags {
        key
        value
      }
      stats {
        ... on RunStatsSnapshot {
          stepsSucceeded
          stepsFailed
          materializations
          expectations
        }
      }
    }
    ... on RunNotFoundError {
      runId
      message
    }
    ... on PythonError {
      message
      stack
    }
  }
}

query ListRuns($filter: RunsFilter, $cursor: String, $limit: Int) {
  runsOrError(filter: $filter, cursor: $cursor, limit: $limit) {
    __typename
    ... on Runs {
      results {
        runId
        status
        creationTime
        startTime
        endTime
        jobName
        tags {
          key
          value
        }
      }
      count
    }
    ... on InvalidPipelineRunsFilterError {
      message
    }
    ... on PythonError {
      message
      stack
    }
  }
}
