[build-system]
requires = ["hatchling>=1.19.0"]
build-backend = "hatchling.build"

[project]
name = "assets_dbt_python"
version = "1!0+dev"
requires-python = ">=3.10,<3.12"
dependencies = [
    "dagster",
    "dagster-cloud",
    "boto3",
    "dagster-dbt",
    "pandas",
    "numpy",
    "scipy",
    "dbt-core",
    "dbt-duckdb",
    "dagster-duckdb",
    "dagster-duckdb-pandas",
]

[tool.dagster]
module_name = "assets_dbt_python.definitions"
code_location_name = "assets_dbt_python"

[dependency-groups]
dev = [
    "dagster-cloud",
    "dagster[test]",
    "dagster-pipes",
    "dagster-shared",
    "dagster-webserver",
    "dagster-pandas",
    "dagster-dbt",
    "dagster-duckdb",
    "dagster-duckdb-pandas",
    "pytest",
    "dagster-dg-cli",
]
[tool.uv]
exclude-newer = "48h"
