/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import airbyteAirbyteOssLogo from './logos/airbyte.svg';

export const logo = airbyteAirbyteOssLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'airbyteAirbyteOss',
  status: 'published',
  name: 'Airbyte',
  title: 'Dagster & Airbyte',
  excerpt:
    'Orchestrate Airbyte connections and schedule syncs alongside upstream or downstream dependencies.',
  partnerlink:
    'https://airbyte.com/tutorials/orchestrate-data-ingestion-and-transformation-pipelines',
  categories: ['ETL'],
  enabledBy: [],
  enables: [],
  tags: ['dagster-supported', 'etl'],
};

export const content =
  'Using this integration, you can trigger Airbyte syncs and orchestrate your Airbyte connections from within Dagster, making it easy to chain an Airbyte sync with upstream or downstream steps in your workflow.\n\n### Installation\n\n```bash\npip install dagster-airbyte\n```\n\n### Example\n\n<CodeExample path="docs_snippets/docs_snippets/integrations/airbyte.py" language="python" />\n\n### About Airbyte\n\n**Airbyte** is an open source data integration engine that helps you consolidate your SaaS application and database data into your data warehouses, lakes and databases.';
