/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import awsCloudwatchLogo from './logos/aws-cloudwatch.svg';

export const logo = awsCloudwatchLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'awsCloudwatch',
  status: 'published',
  name: 'CloudWatch',
  title: 'Dagster & AWS CloudWatch',
  excerpt:
    'This integration allows you to send Dagster logs to AWS CloudWatch, enabling centralized logging and monitoring of your Dagster jobs.',
  partnerlink: 'https://aws.amazon.com/',
  categories: ['Monitoring'],
  enabledBy: [],
  enables: [],
  tags: ['dagster-supported', 'monitoring'],
};

export const content =
  'import Deprecated from \'@site/docs/partials/\\_Deprecated.md\';\n\n<Deprecated />\n\nThis integration allows you to send Dagster logs to AWS CloudWatch, enabling centralized logging and monitoring of your Dagster jobs. By using AWS CloudWatch, you can take advantage of its powerful log management features, such as real-time log monitoring, log retention policies, and alerting capabilities.\n\nUsing this integration, you can configure your Dagster jobs to log directly to AWS CloudWatch, making it easier to track and debug your workflows. This is particularly useful for production environments where centralized logging is essential for maintaining observability and operational efficiency.\n\n### Installation\n\n```bash\npip install dagster-aws\n```\n\n### Examples\n\n<CodeExample path="docs_snippets/docs_snippets/integrations/aws-cloudwatch.py" language="python" />\n\n### About AWS CloudWatch\n\nAWS CloudWatch is a monitoring and observability service provided by Amazon Web Services (AWS). It allows you to collect, access, and analyze performance and operational data from a variety of AWS resources, applications, and services. With AWS CloudWatch, you can set up alarms, visualize logs and metrics, and gain insights into your infrastructure and applications to ensure they\'re running smoothly.\n\nAWS CloudWatch provides features such as:\n\n- Real-time monitoring: Track the performance of your applications and infrastructure in real-time.\n- Log management: Collect, store, and analyze log data from various sources.\n- Alarms and notifications: Set up alarms to automatically notify you of potential issues.\n- Dashboards: Create custom dashboards to visualize metrics and logs.\n- Integration with other AWS services: Seamlessly integrate with other AWS services for a comprehensive monitoring solution.';
