/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import awsEmrLogo from './logos/aws-emr.svg';

export const logo = awsEmrLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'awsEmr',
  status: 'published',
  name: 'EMR',
  title: 'Dagster & AWS EMR',
  excerpt:
    'The AWS EMR integration allows you to seamlessly integrate AWS EMR into your Dagster pipelines for petabyte-scale data processing using open source tools like Apache Spark, Hive, Presto, and more.',
  partnerlink: 'https://aws.amazon.com/',
  categories: ['Compute'],
  enabledBy: [],
  enables: [],
  tags: ['dagster-supported', 'compute'],
};

export const content =
  'The `dagster-aws` integration provides ways orchestrating data pipelines that leverage AWS services, including AWS EMR (Elastic MapReduce). This integration allows you to run and scale big data workloads using open source tools such as Apache Spark, Hive, Presto, and more.\n\nUsing this integration, you can:\n\n- Seamlessly integrate AWS EMR into your Dagster pipelines.\n- Utilize EMR for petabyte-scale data processing.\n- Easily manage and monitor EMR clusters and jobs from within Dagster.\n- Leverage Dagster\'s orchestration capabilities to handle complex data workflows involving EMR.\n\n### Installation\n\n```bash\npip install dagster-aws\n```\n\n### Examples\n\n<CodeExample path="docs_snippets/docs_snippets/integrations/aws-emr.py" language="python" />\n\n### About AWS EMR\n\n**AWS EMR** (Elastic MapReduce) is a cloud big data platform for processing vast amounts of data using open source tools such as Apache Spark, Apache Hive, Apache HBase, Apache Flink, Apache Hudi, and Presto. It simplifies running big data frameworks, allowing you to process and analyze large datasets quickly and cost-effectively. AWS EMR provides the scalability, flexibility, and reliability needed to handle complex data processing tasks, making it an ideal choice for data engineers and scientists.';
