/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import awsSecretsmanagerLogo from './logos/aws-secretsmanager.svg';

export const logo = awsSecretsmanagerLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'awsSecretsmanager',
  status: 'published',
  name: 'Secrets Manager',
  title: 'Dagster & AWS Secrets Manager',
  excerpt:
    'This integration allows you to manage, retrieve, and rotate credentials, API keys, and other secrets using AWS Secrets Manager.',
  partnerlink: 'https://aws.amazon.com/',
  categories: ['Other'],
  enabledBy: [],
  enables: [],
  tags: ['dagster-supported'],
};

export const content =
  'import Beta from \'@site/docs/partials/\\_Beta.md\';\n\n<Beta />\n\nThis integration allows you to manage, retrieve, and rotate credentials, API keys, and other secrets using [AWS Secrets Manager](https://aws.amazon.com/secrets-manager/).\n\n### Installation\n\n```bash\npip install dagster-aws\n```\n\n### Examples\n\n<CodeExample path="docs_snippets/docs_snippets/integrations/aws-secretsmanager.py" language="python" />\n\n### About AWS Secrets Manager\n\n**AWS Secrets Manager** helps you protect access to your applications, services, and IT resources without the upfront cost and complexity of managing your own hardware security module infrastructure. With Secrets Manager, you can rotate, manage, and retrieve database credentials, API keys, and other secrets throughout their lifecycle. Users and applications retrieve secrets with a call to Secrets Manager APIs, eliminating the need to hardcode sensitive information in plain text.';
