/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import azureAdls2Logo from './logos/azure.svg';

export const logo = azureAdls2Logo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'azureAdls2',
  status: 'published',
  name: '',
  title: 'Dagster &  Azure Data Lake Storage Gen 2',
  excerpt: 'Get utilities for ADLS2 and Blob Storage.',
  partnerlink: 'https://azure.microsoft.com/',
  categories: ['Storage'],
  enabledBy: [],
  enables: [],
  tags: ['dagster-supported', 'storage'],
};

export const content =
  'Dagster helps you use Azure Storage Accounts as part of your data pipeline. Azure Data Lake Storage Gen 2 (ADLS2) is our primary focus but we also provide utilities for Azure Blob Storage.\n\n### Installation\n\n```bash\npip install dagster-azure\n```\n\n### Example\n\n<CodeExample path="docs_snippets/docs_snippets/integrations/azure-adls2.py" language="python" />\n\nIn this updated code, we use `ADLS2Resource` directly instead of `adls2_resource`. The configuration is passed to `ADLS2Resource` during its instantiation.\n\n### About Azure Data Lake Storage Gen 2 (ADLS2)\n\n**Azure Data Lake Storage Gen 2 (ADLS2)** is a set of capabilities dedicated to big data analytics, built on Azure Blob Storage. ADLS2 combines the scalability, cost-effectiveness, security, and rich capabilities of Azure Blob Storage with a high-performance file system that\'s built for analytics and is compatible with the Hadoop Distributed File System (HDFS). This makes it an ideal choice for data lakes and big data analytics.';
