/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import databricksLogo from './logos/databricks.svg';

export const logo = databricksLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'databricks',
  status: 'published',
  name: 'Databricks',
  title: 'Dagster & Databricks',
  excerpt:
    'The Databricks integration enables you to initiate Databricks jobs directly from Dagster, seamlessly pass parameters to your code, and stream logs and structured messages back into Dagster.',
  partnerlink: 'https://databricks.com/',
  categories: ['Compute'],
  enabledBy: [],
  enables: [],
  tags: ['dagster-supported', 'compute'],
};

export const content =
  'The `dagster-databricks` integration library provides the `PipesDatabricksClient` resource, enabling you to launch Databricks jobs directly from Dagster assets and ops. This integration allows you to pass parameters to Databricks code while Dagster receives real-time events, such as logs, asset checks, and asset materializations, from the initiated jobs. With minimal code changes required on the job side, this integration is both efficient and easy to implement.\n\n### Installation\n\n```bash\npip install dagster-databricks\n```\n\n### Example\n\n<CodeExample path="docs_snippets/docs_snippets/integrations/databricks/dagster_code.py" language="python" />\n\n<CodeExample path="docs_snippets/docs_snippets/integrations/databricks/databricks_code.py" language="python" />\n\n### About Databricks\n\n**Databricks** is a unified data analytics platform that simplifies and accelerates the process of building big data and AI solutions. It integrates seamlessly with Apache Spark and offers support for various data sources and formats. Databricks provides powerful tools to create, run, and manage data pipelines, making it easier to handle complex data engineering tasks. Its collaborative and scalable environment is ideal for data engineers, scientists, and analysts who need to process and analyze large datasets efficiently.';
