/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import dbtLogo from './logos/dbt.svg';

export const logo = dbtLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'dbt',
  status: 'published',
  name: 'dbt',
  title: 'Dagster & dbt',
  excerpt: '',
  partnerlink: '',
  categories: [],
  enabledBy: [],
  enables: [],
  tags: [],
};

export const content = "import DocCardList from '@theme/DocCardList';\n\n<DocCardList />";
