/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import githubLogo from './logos/github.svg';

export const logo = githubLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'github',
  status: 'published',
  name: 'GitHub',
  title: 'Dagster & GitHub',
  excerpt: 'Integrate with GitHub Apps and automate operations within your github repositories.',
  partnerlink: 'https://github.com/',
  categories: ['Other'],
  enabledBy: [],
  enables: [],
  tags: ['dagster-supported'],
};

export const content =
  'import Deprecated from \'@site/docs/partials/\\_Deprecated.md\';\n\n<Deprecated />\n\nThis library provides an integration with _[GitHub Apps](https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps)_ by providing a thin wrapper on the GitHub v4 GraphQL API. This allows for automating operations within your GitHub repositories and with the tighter permissions scopes that GitHub Apps allow for vs using a personal token.\n\n### Installation\n\n```bash\npip install dagster-github\n```\n\n### Example\n\n<CodeExample path="docs_snippets/docs_snippets/integrations/github.py" language="python" />\n\n### About GitHub\n\n**GitHub** provides a highly available git repo, access control, bug tracking, software feature requests, task management, continuous integration, and wikis for open source and commercial projects.';
