/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import hightouchLogo from './logos/hightouch.svg';

export const logo = hightouchLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'hightouch',
  status: 'published',
  name: 'Hightouch',
  title: 'Dagster & Hightouch',
  excerpt: 'Trigger syncs and monitor them until they complete.',
  partnerlink: 'https://hightouch.com/',
  categories: ['ETL'],
  enabledBy: [],
  enables: [],
  tags: ['community-supported', 'etl'],
};

export const content =
  'With this integration you can trigger Hightouch syncs and monitor them from within Dagster. Fine-tune when Hightouch syncs kick-off, visualize their dependencies, and monitor the steps in your data activation workflow.\n\nThis native integration helps your team more effectively orchestrate the last mile of data analytics—bringing that data from the warehouse back into the SaaS tools your business teams live in. With the `dagster-hightouch` integration, Hightouch users have more granular and sophisticated control over when data gets activated.\n\n### Installation\n\n```bash\npip install dagster-hightouch\n```\n\n### Example\n\n<CodeExample path="docs_snippets/docs_snippets/integrations/hightouch.py" language="python" />\n\n### About Hightouch\n\n**Hightouch** syncs data from any data warehouse into popular SaaS tools that businesses run on. Hightouch uses the power of Reverse ETL to transform core business applications from isolated data islands into powerful integrated solutions.';
