/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import javaLogo from './logos/java.svg';

export const logo = javaLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'java',
  status: 'published',
  name: 'Java',
  title: 'Dagster & Java',
  excerpt:
    'The Java Pipes client provides a Java implementation of the Dagster Pipes protocol that can be used to orchestrate data processing pipelines written in Java from Dagster, while receiving logs and metadata from the Java application.',
  partnerlink: 'https://www.java.com/en/',
  categories: [],
  enabledBy: [],
  enables: [],
  tags: ['dagster-supported'],
};

export const content =
  'The Java Pipes client provides a Java implementation of the Dagster Pipes protocol that can be used to orchestrate data processing pipelines written in Java from Dagster, while receiving logs and metadata from the Java application.\n\n### Installation and examples\n\nFor installation information and examples, see the [community integrations GitHub repository](https://github.com/dagster-io/community-integrations/blob/main/libraries/pipes/implementations/java/README.md).\n\n### About Java\n\n[Java](https://www.java.com/en/) is a programming language and computing platform first released by Sun Microsystems in 1995. It has evolved from humble beginnings to power a large share of today’s digital world, by providing the reliable platform upon which many services and applications are built. New, innovative products and digital services designed for the future continue to rely on Java, as well. To get started with Java, see the [Java developer resources](https://dev.java/).';
