/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import openaiLogo from './logos/openai.svg';

export const logo = openaiLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'openai',
  status: 'published',
  name: 'OpenAI',
  title: 'Dagster & OpenAI',
  excerpt: 'Integrate OpenAI calls into your Dagster pipelines, without breaking the bank.',
  partnerlink: 'https://platform.openai.com/docs/introduction',
  categories: ['Other'],
  enabledBy: [],
  enables: [],
  tags: ['dagster-supported'],
};

export const content =
  'The `dagster-openai` library allows you to easily interact with the OpenAI REST API using the OpenAI Python API to build AI steps into your Dagster pipelines. You can also log OpenAI API usage metadata in Dagster Insights, giving you detailed observability on API call credit consumption.\n\nWhen paired with Dagster assets, the resource automatically logs OpenAI usage metadata in asset metadata.\n\n### Installation\n\n```bash\npip install dagster dagster-openai\n```\n\n### Example\n\n<CodeExample path="docs_snippets/docs_snippets/integrations/openai.py" language="python" />\n\n### About OpenAI\n\nOpenAI is a U.S. based artificial intelligence (AI) research organization with the goal of developing "safe and beneficial" artificial general intelligence, which it defines as "highly autonomous systems that outperform humans at most economically valuable work".';
