/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import panderaLogo from './logos/pandera.svg';

export const logo = panderaLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'pandera',
  status: 'published',
  name: 'Pandera',
  title: 'Dagster & Pandera',
  excerpt: 'Generate Dagster Types from Pandera dataframe schemas.',
  partnerlink: 'https://pandera.readthedocs.io/en/stable/',
  categories: ['Metadata'],
  enabledBy: [],
  enables: [],
  tags: ['dagster-supported', 'metadata'],
};

export const content =
  'import Beta from \'@site/docs/partials/\\_Beta.md\';\n\n<Beta />\n\nThe `dagster-pandera` integration library provides an API for generating Dagster Types from [Pandera DataFrame schemas](https://pandera.readthedocs.io/en/stable/dataframe_schemas.html).\n\nLike all Dagster types, Dagster-Pandera-generated types can be used to annotate op inputs and outputs. This provides runtime type-checking with rich error reporting and allows Dagster UI to display information about a DataFrame\'s structure.\n\n:::note\n\nCurrently, `dagster-pandera` only supports pandas and Polars dataframes, despite Pandera supporting validation on other dataframe backends.\n\n:::\n\n### Installation\n\n```bash\npip install dagster-pandera\n```\n\n### Example\n\n<CodeExample path="docs_snippets/docs_snippets/integrations/pandera.py" language="python" />\n\n### About Pandera\n\n**Pandera** is a statistical data testing toolkit, and a data validation library for scientists, engineers, and analysts seeking correctness.';
