/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import perianLogo from './logos/perian.png';

export const logo = perianLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'perian',
  status: 'published',
  name: 'Perian',
  title: 'Dagster & Perian',
  excerpt:
    "The `dagster-perian` integration allows you to easily dockerize your codebase and execute it on the PERIAN platform, PERIAN's serverless GPU environment.",
  partnerlink: '',
  categories: [],
  enabledBy: [],
  enables: [],
  tags: ['community-supported', 'compute'],
};

export const content =
  "The `dagster-perian` integration allows you to easily dockerize your codebase and execute it on the PERIAN platform, PERIAN's serverless GPU environment.\n\nFor more information, please visit the [dagster-perian GitHub repository](https://github.com/Perian-io/dagster-perian) and the [PERIAN documentation](https://perian.io/docs).";
