/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import rayLogo from './logos/ray.svg';

export const logo = rayLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'ray',
  status: 'published',
  name: 'Ray',
  title: 'Dagster & Ray',
  excerpt:
    'The community-supported `dagster-ray` package allows orchestrating distributed Ray compute from Dagster pipelines.',
  partnerlink: '',
  categories: [],
  enabledBy: [],
  enables: [],
  tags: ['community-supported', 'etl'],
};

export const content =
  'The community-supported `dagster-ray` package allows orchestrating distributed Ray compute from Dagster pipelines.\n\nFor more information, see the [dagster-ray GitHub repository](https://github.com/danielgafni/dagster-ray).';
