/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import twilioLogo from './logos/twilio.svg';

export const logo = twilioLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'twilio',
  status: 'published',
  name: 'Twilio',
  title: 'Dagster & Twilio',
  excerpt: 'Integrate Twilio tasks into your data pipeline runs.',
  partnerlink: 'https://www.twilio.com/',
  categories: ['Alerting'],
  enabledBy: [],
  enables: [],
  tags: ['dagster-supported', 'alerting'],
};

export const content =
  'Use your Twilio `Account SID` and `Auth Token` to build Twilio tasks right into your Dagster pipeline.\n\n### Installation\n\n```bash\npip install dagster-twilio\n```\n\n### Example\n\n\n```python\n# Read the docs on Resources to learn more: https://docs.dagster.io/deployment/resources\nfrom dagster_twilio import TwilioResource\n\nimport dagster as dg\n\n\n@dg.asset\ndef twilio_message(twilio: TwilioResource):\n    twilio.get_client().messages.create(\n        to="+15551234567", from_="+15558901234", body="Hello world!"\n    )\n\n\ndefs = dg.Definitions(\n    assets=[twilio_message],\n    resources={\n        "twilio": TwilioResource(\n            account_sid=dg.EnvVar("TWILIO_ACCOUNT_SID"),\n            auth_token=dg.EnvVar("TWILIO_AUTH_TOKEN"),\n        )\n    },\n)\n```\n        \n\n### About Twilio\n\n**Twilio** provides communication APIs for phone calls, text messages, and other communication functions.';
