/**
 * THIS FILE IS GENERATED BY `yarn generate-integration-docs`.
 *
 * DO NOT EDIT MANUALLY.
 */

import {IntegrationFrontmatter} from '../types';
import typescriptLogo from './logos/typescript.svg';

export const logo = typescriptLogo;

export const frontmatter: IntegrationFrontmatter = {
  id: 'typescript',
  status: 'published',
  name: 'TypeScript',
  title: 'Dagster & TypeScript',
  excerpt:
    'The TypeScript Pipes client allows integration between any TypeScript process and the Dagster orchestrator.',
  partnerlink: 'https://www.typescriptlang.org/',
  categories: [],
  enabledBy: [],
  enables: [],
  tags: ['dagster-supported'],
};

export const content =
  'The [`dagster-pipes-typescript` npm package](https://www.npmjs.com/package/@dagster-io/dagster-pipes) is a Dagster Pipes implementation for the TypeScript programming language that allows integration between any TypeScript process and the Dagster orchestrator.\n\nFor more information, see the [community integrations GitHub repository](https://github.com/dagster-io/community-integrations/blob/main/libraries/pipes/implementations/typescript/README.md).\n\n### Prerequisites\n\n- [Install node and npm](https://nodejs.org/en/download)\n- Install the typescript compiler (`npm install -g typescript`)\n\n### Installation\n\n`@dagster-io/dagster-pipes` is available as an npm package:\n\n```sh\nnpm install @dagster-io/dagster-pipes\n```\n\n### Example\n\nFor a usage example, see the [README](https://github.com/dagster-io/community-integrations/blob/main/libraries/pipes/implementations/typescript/README.md) in the community integrations repository.\n\n### About Typescript\n\n[TypeScript](https://www.typescriptlang.org/) is a strongly typed programming language that builds on JavaScript, giving you better tooling at any scale. To get started with TypeScript, see the [TypeScript docs](https://www.typescriptlang.org/docs/).';
