ARG BASE_IMAGE
ARG PYTHON_VERSION

FROM "${BASE_IMAGE}"

# Prevent telemetry from being sent in image
ENV BUILDKITE=true

COPY . .

RUN pip install \
    -e modules/dagster \
    -e .

WORKDIR /dagster_test/dagster_core_docker_buildkite/

EXPOSE 80
