FROM python:3.8-slim

COPY . /
RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker \
    dagster-graphql \
    dagit

ENV DAGSTER_HOME=/opt/dagster/dagster_home/
RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
