FROM python:3.8-slim

COPY ./python_modules/ /tmp/python_modules/

WORKDIR /tmp

RUN pip install \
    -e python_modules/dagster \
    -e python_modules/dagster-graphql \
    -e python_modules/dagit \
    -e python_modules/libraries/dagster-postgres \
    -e python_modules/libraries/dagster-docker


ENV DAGSTER_HOME=/opt/dagster/dagster_home/
RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
