FROM python:3.8-slim

ARG DAGIT_BACKCOMPAT_VERSION
ARG DAGIT_BACKCOMPAT_LIBRARY_VERSION

COPY pins.txt pins.txt

RUN pip install \
    -r pins.txt \
    dagster=="${DAGIT_BACKCOMPAT_VERSION}" \
    dagster-postgres=="${DAGIT_BACKCOMPAT_LIBRARY_VERSION}" \
    dagster-docker=="${DAGIT_BACKCOMPAT_LIBRARY_VERSION}" \
    dagster-graphql=="${DAGIT_BACKCOMPAT_VERSION}" \
    dagit=="${DAGIT_BACKCOMPAT_VERSION}"

ENV DAGSTER_HOME=/opt/dagster/dagster_home/
RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
