FROM python:3.8-slim

ARG DAGIT_BACKCOMPAT_VERSION


RUN pip install \
    dagster=="${DAGIT_BACKCOMPAT_VERSION}" \
    dagster-postgres=="${DAGIT_BACKCOMPAT_VERSION}" \
    dagster-docker=="${DAGIT_BACKCOMPAT_VERSION}" \
    dagster-graphql=="${DAGIT_BACKCOMPAT_VERSION}" \
    dagit=="${DAGIT_BACKCOMPAT_VERSION}"

ENV DAGSTER_HOME=/opt/dagster/dagster_home/
RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
