[tox]
requires =
    tox-uv>=1.16
skipsdist = true

[testenv]
runner = uv-venv-lock-runner
uv_sync_locked = false
uv_sync_flags = --frozen
download = True
passenv =
    CI_*
    BUILDKITE*
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
dependency_groups =
    test
allowlist_externals =
  /bin/bash
  uv
  just
commands =
  # We need to rebuild the UI to ensure that the dagster-webserver can run
  just -f ../../justfile rebuild_ui
  !windows: /bin/bash -c '! uv pip list --exclude-editable | grep -e dagster'
  pytest ./airlift_federation_tutorial_tests --snapshot-warn-unused -vv {posargs}
