FROM python:3.7-slim

ARG DAGSTER_GIT_COMMIT=origin/master

WORKDIR /tmp

# Install git
RUN apt-get update -y && apt-get install -y git

# Checkout and install dagster libraries needed for the daemon and to load the DagsterInstance
RUN git clone https://github.com/dagster-io/dagster.git dagster \
    && cd dagster \
    && git checkout ${DAGSTER_GIT_COMMIT}

WORKDIR /tmp/dagster

RUN pip install \
    -e python_modules/dagster \
    -e python_modules/libraries/dagster-postgres \
    -e python_modules/libraries/dagster-docker

# Set $DAGSTER_HOME and copy dagster instance YAML there

ENV DAGSTER_HOME=/opt/dagster/dagster_home

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME

# Start daemon loop

ENTRYPOINT ["dagster-daemon", "run"]