import dagster as dg


@dg.asset(
    deps=[
        "cleaned_transactions",
        "risky_customers",
        "risky_transactions",
    ]
)
def aggregated_metrics():
    """An asset that depends on all ETL tables generated by the component."""
    ...
