# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import IssueFields


class AddLinkToIssue(BaseModel):
    add_link_to_issue: Union[
        "AddLinkToIssueAddLinkToIssueUpdateIssueSuccess",
        "AddLinkToIssueAddLinkToIssuePythonError",
        "AddLinkToIssueAddLinkToIssueUnauthorizedError",
    ] = Field(alias="addLinkToIssue", discriminator="typename__")


class AddLinkToIssueAddLinkToIssueUpdateIssueSuccess(BaseModel):
    typename__: Literal["UpdateIssueSuccess"] = Field(alias="__typename")
    issue: "AddLinkToIssueAddLinkToIssueUpdateIssueSuccessIssue"


class AddLinkToIssueAddLinkToIssueUpdateIssueSuccessIssue(IssueFields):
    pass


class AddLinkToIssueAddLinkToIssuePythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str


class AddLinkToIssueAddLinkToIssueUnauthorizedError(BaseModel):
    typename__: Literal["UnauthorizedError"] = Field(alias="__typename")
    message: str


AddLinkToIssue.model_rebuild()
AddLinkToIssueAddLinkToIssueUpdateIssueSuccess.model_rebuild()
