# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import AlertPolicyFields


class CreateOrUpdateAlertPolicy(BaseModel):
    create_or_update_alert_policy_from_document: Union[
        "CreateOrUpdateAlertPolicyCreateOrUpdateAlertPolicyFromDocumentAlertPolicy",
        "CreateOrUpdateAlertPolicyCreateOrUpdateAlertPolicyFromDocumentPythonError",
        "CreateOrUpdateAlertPolicyCreateOrUpdateAlertPolicyFromDocumentUnauthorizedError",
        "CreateOrUpdateAlertPolicyCreateOrUpdateAlertPolicyFromDocumentInvalidAlertPolicyError",
    ] = Field(alias="createOrUpdateAlertPolicyFromDocument", discriminator="typename__")


class CreateOrUpdateAlertPolicyCreateOrUpdateAlertPolicyFromDocumentAlertPolicy(
    AlertPolicyFields
):
    typename__: Literal["AlertPolicy"] = Field(alias="__typename")


class CreateOrUpdateAlertPolicyCreateOrUpdateAlertPolicyFromDocumentPythonError(
    BaseModel
):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str
    stack: list[str]


class CreateOrUpdateAlertPolicyCreateOrUpdateAlertPolicyFromDocumentUnauthorizedError(
    BaseModel
):
    typename__: Literal["UnauthorizedError"] = Field(alias="__typename")
    message: str


class CreateOrUpdateAlertPolicyCreateOrUpdateAlertPolicyFromDocumentInvalidAlertPolicyError(
    BaseModel
):
    typename__: Literal["InvalidAlertPolicyError"] = Field(alias="__typename")
    message: str


CreateOrUpdateAlertPolicy.model_rebuild()
