# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import IssueFields


class CreateIssue(BaseModel):
    create_issue: Union[
        "CreateIssueCreateIssueCreateIssueSuccess",
        "CreateIssueCreateIssuePythonError",
        "CreateIssueCreateIssueUnauthorizedError",
    ] = Field(alias="createIssue", discriminator="typename__")


class CreateIssueCreateIssueCreateIssueSuccess(BaseModel):
    typename__: Literal["CreateIssueSuccess"] = Field(alias="__typename")
    issue: "CreateIssueCreateIssueCreateIssueSuccessIssue"


class CreateIssueCreateIssueCreateIssueSuccessIssue(IssueFields):
    pass


class CreateIssueCreateIssuePythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str


class CreateIssueCreateIssueUnauthorizedError(BaseModel):
    typename__: Literal["UnauthorizedError"] = Field(alias="__typename")
    message: str


CreateIssue.model_rebuild()
CreateIssueCreateIssueCreateIssueSuccess.model_rebuild()
