# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import DagsterCloudDeploymentType


class DeleteDeployment(BaseModel):
    delete_deployment: Union[
        "DeleteDeploymentDeleteDeploymentDagsterCloudDeployment",
        "DeleteDeploymentDeleteDeploymentDeploymentNotFoundError",
        "DeleteDeploymentDeleteDeploymentDeleteFinalDeploymentError",
        "DeleteDeploymentDeleteDeploymentUnauthorizedError",
        "DeleteDeploymentDeleteDeploymentPythonError",
    ] = Field(alias="deleteDeployment", discriminator="typename__")


class DeleteDeploymentDeleteDeploymentDagsterCloudDeployment(BaseModel):
    typename__: Literal["DagsterCloudDeployment"] = Field(alias="__typename")
    deployment_id: int = Field(alias="deploymentId")
    deployment_name: str = Field(alias="deploymentName")
    deployment_type: DagsterCloudDeploymentType = Field(alias="deploymentType")


class DeleteDeploymentDeleteDeploymentDeploymentNotFoundError(BaseModel):
    typename__: Literal["DeploymentNotFoundError"] = Field(alias="__typename")


class DeleteDeploymentDeleteDeploymentDeleteFinalDeploymentError(BaseModel):
    typename__: Literal["DeleteFinalDeploymentError"] = Field(alias="__typename")


class DeleteDeploymentDeleteDeploymentUnauthorizedError(BaseModel):
    typename__: Literal["UnauthorizedError"] = Field(alias="__typename")


class DeleteDeploymentDeleteDeploymentPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str


DeleteDeployment.model_rebuild()
