# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Annotated, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import IssueStatus


class IssueFields(BaseModel):
    public_id: str = Field(alias="publicId")
    title: str
    description: str
    status: IssueStatus
    context: Optional[str]
    linked_objects: List[
        Annotated[
            Union["IssueFieldsLinkedObjectsAsset", "IssueFieldsLinkedObjectsRun"],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="linkedObjects")
    created_by: Optional[
        Annotated[
            Union[
                "IssueFieldsCreatedByServiceUser",
                "IssueFieldsCreatedByDagsterCloudUser",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="createdBy")


class IssueFieldsLinkedObjectsAsset(BaseModel):
    typename__: Literal["Asset"] = Field(alias="__typename")
    key: "IssueFieldsLinkedObjectsAssetKey"


class IssueFieldsLinkedObjectsAssetKey(BaseModel):
    path: List[str]


class IssueFieldsLinkedObjectsRun(BaseModel):
    typename__: Literal["Run"] = Field(alias="__typename")
    id: str


class IssueFieldsCreatedByServiceUser(BaseModel):
    typename__: Literal["ServiceUser"] = Field(alias="__typename")
    display_name: str = Field(alias="displayName")


class IssueFieldsCreatedByDagsterCloudUser(BaseModel):
    typename__: Literal["DagsterCloudUser"] = Field(alias="__typename")
    display_name: str = Field(alias="displayName")


class SecretFields(BaseModel):
    id: str
    secret_name: str = Field(alias="secretName")
    updated_by: Optional["SecretFieldsUpdatedBy"] = Field(alias="updatedBy")
    update_timestamp: Optional[float] = Field(alias="updateTimestamp")
    location_names: List[str] = Field(alias="locationNames")
    full_deployment_scope: bool = Field(alias="fullDeploymentScope")
    all_branch_deployments_scope: bool = Field(alias="allBranchDeploymentsScope")
    specific_branch_deployment_scope: Optional[str] = Field(
        alias="specificBranchDeploymentScope"
    )
    local_deployment_scope: bool = Field(alias="localDeploymentScope")
    can_view_secret_value: bool = Field(alias="canViewSecretValue")
    can_edit_secret: bool = Field(alias="canEditSecret")


class SecretFieldsUpdatedBy(BaseModel):
    email: str


IssueFields.model_rebuild()
SecretFields.model_rebuild()
