# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import InstigationStatus, SensorType


class GetSensor(BaseModel):
    sensor_or_error: Union[
        "GetSensorSensorOrErrorSensor",
        "GetSensorSensorOrErrorSensorNotFoundError",
        "GetSensorSensorOrErrorUnauthorizedError",
        "GetSensorSensorOrErrorPythonError",
    ] = Field(alias="sensorOrError", discriminator="typename__")


class GetSensorSensorOrErrorSensor(BaseModel):
    typename__: Literal["Sensor"] = Field(alias="__typename")
    id: str
    name: str
    sensor_state: "GetSensorSensorOrErrorSensorSensorState" = Field(alias="sensorState")
    sensor_type: SensorType = Field(alias="sensorType")
    description: Optional[str]


class GetSensorSensorOrErrorSensorSensorState(BaseModel):
    status: InstigationStatus


class GetSensorSensorOrErrorSensorNotFoundError(BaseModel):
    typename__: Literal["SensorNotFoundError"] = Field(alias="__typename")
    message: str


class GetSensorSensorOrErrorUnauthorizedError(BaseModel):
    typename__: Literal["UnauthorizedError"] = Field(alias="__typename")
    message: str


class GetSensorSensorOrErrorPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str


GetSensor.model_rebuild()
GetSensorSensorOrErrorSensor.model_rebuild()
