# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from pydantic import Field

from .base_model import BaseModel


class GetAssetLocations(BaseModel):
    asset_nodes: list["GetAssetLocationsAssetNodes"] = Field(alias="assetNodes")


class GetAssetLocationsAssetNodes(BaseModel):
    asset_key: "GetAssetLocationsAssetNodesAssetKey" = Field(alias="assetKey")
    repository: "GetAssetLocationsAssetNodesRepository"


class GetAssetLocationsAssetNodesAssetKey(BaseModel):
    path: list[str]


class GetAssetLocationsAssetNodesRepository(BaseModel):
    name: str
    location: "GetAssetLocationsAssetNodesRepositoryLocation"


class GetAssetLocationsAssetNodesRepositoryLocation(BaseModel):
    name: str


GetAssetLocations.model_rebuild()
GetAssetLocationsAssetNodes.model_rebuild()
GetAssetLocationsAssetNodesRepository.model_rebuild()
