# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Annotated, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class GetAssetConditionEvaluations(BaseModel):
    asset_condition_evaluation_records_or_error: Optional[
        Annotated[
            Union[
                "GetAssetConditionEvaluationsAssetConditionEvaluationRecordsOrErrorAssetConditionEvaluationRecords",
                "GetAssetConditionEvaluationsAssetConditionEvaluationRecordsOrErrorAutoMaterializeAssetEvaluationNeedsMigrationError",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="assetConditionEvaluationRecordsOrError")


class GetAssetConditionEvaluationsAssetConditionEvaluationRecordsOrErrorAssetConditionEvaluationRecords(
    BaseModel
):
    typename__: Literal["AssetConditionEvaluationRecords"] = Field(alias="__typename")
    records: List[
        "GetAssetConditionEvaluationsAssetConditionEvaluationRecordsOrErrorAssetConditionEvaluationRecordsRecords"
    ]


class GetAssetConditionEvaluationsAssetConditionEvaluationRecordsOrErrorAssetConditionEvaluationRecordsRecords(
    BaseModel
):
    evaluation_id: str = Field(alias="evaluationId")
    timestamp: float
    num_requested: Optional[int] = Field(alias="numRequested")
    run_ids: List[str] = Field(alias="runIds")
    start_timestamp: Optional[float] = Field(alias="startTimestamp")
    end_timestamp: Optional[float] = Field(alias="endTimestamp")
    root_unique_id: str = Field(alias="rootUniqueId")
    evaluation_nodes: List[
        "GetAssetConditionEvaluationsAssetConditionEvaluationRecordsOrErrorAssetConditionEvaluationRecordsRecordsEvaluationNodes"
    ] = Field(alias="evaluationNodes")


class GetAssetConditionEvaluationsAssetConditionEvaluationRecordsOrErrorAssetConditionEvaluationRecordsRecordsEvaluationNodes(
    BaseModel
):
    unique_id: str = Field(alias="uniqueId")
    user_label: Optional[str] = Field(alias="userLabel")
    expanded_label: List[str] = Field(alias="expandedLabel")
    start_timestamp: Optional[float] = Field(alias="startTimestamp")
    end_timestamp: Optional[float] = Field(alias="endTimestamp")
    num_true: Optional[int] = Field(alias="numTrue")
    num_candidates: Optional[int] = Field(alias="numCandidates")
    is_partitioned: bool = Field(alias="isPartitioned")
    child_unique_ids: List[str] = Field(alias="childUniqueIds")
    operator_type: str = Field(alias="operatorType")


class GetAssetConditionEvaluationsAssetConditionEvaluationRecordsOrErrorAutoMaterializeAssetEvaluationNeedsMigrationError(
    BaseModel
):
    typename__: Literal["AutoMaterializeAssetEvaluationNeedsMigrationError"] = Field(
        alias="__typename"
    )
    message: str


GetAssetConditionEvaluations.model_rebuild()
GetAssetConditionEvaluationsAssetConditionEvaluationRecordsOrErrorAssetConditionEvaluationRecords.model_rebuild()
GetAssetConditionEvaluationsAssetConditionEvaluationRecordsOrErrorAssetConditionEvaluationRecordsRecords.model_rebuild()
