# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Annotated, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class GetLogsCapturedEvents(BaseModel):
    logs_for_run: Union[
        "GetLogsCapturedEventsLogsForRunEventConnection",
        "GetLogsCapturedEventsLogsForRunRunNotFoundError",
        "GetLogsCapturedEventsLogsForRunPythonError",
    ] = Field(alias="logsForRun", discriminator="typename__")


class GetLogsCapturedEventsLogsForRunEventConnection(BaseModel):
    typename__: Literal["EventConnection"] = Field(alias="__typename")
    events: List[
        Annotated[
            Union[
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepFailureEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepInputEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepOutputEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepSkippedEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepStartEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepSuccessEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepUpForRetryEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepRestartEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsHealthChangedEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsLogMessageEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsResourceInitFailureEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsResourceInitStartedEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsResourceInitSuccessEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsRunFailureEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsRunStartEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsRunEnqueuedEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsRunDequeuedEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsRunStartingEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsRunCancelingEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsRunCanceledEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsRunSuccessEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsStepWorkerStartedEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsStepWorkerStartingEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsHandledOutputEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsLoadedInputEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsLogsCapturedEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsObjectStoreOperationEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsStepExpectationResultEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsMaterializationEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsObservationEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsFailedToMaterializeEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsEngineEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsHookCompletedEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsHookSkippedEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsHookErroredEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsAlertStartEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsAlertSuccessEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsAlertFailureEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsAssetMaterializationPlannedEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsAssetCheckEvaluationPlannedEvent",
                "GetLogsCapturedEventsLogsForRunEventConnectionEventsAssetCheckEvaluationEvent",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    cursor: str
    has_more: bool = Field(alias="hasMore")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepFailureEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepFailureEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepInputEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepInputEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepOutputEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepOutputEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepSkippedEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepSkippedEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepStartEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepStartEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepSuccessEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepSuccessEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepUpForRetryEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepUpForRetryEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsExecutionStepRestartEvent(
    BaseModel
):
    typename__: Literal["ExecutionStepRestartEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsHealthChangedEvent(BaseModel):
    typename__: Literal["HealthChangedEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsLogMessageEvent(BaseModel):
    typename__: Literal["LogMessageEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsResourceInitFailureEvent(
    BaseModel
):
    typename__: Literal["ResourceInitFailureEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsResourceInitStartedEvent(
    BaseModel
):
    typename__: Literal["ResourceInitStartedEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsResourceInitSuccessEvent(
    BaseModel
):
    typename__: Literal["ResourceInitSuccessEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsRunFailureEvent(BaseModel):
    typename__: Literal["RunFailureEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsRunStartEvent(BaseModel):
    typename__: Literal["RunStartEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsRunEnqueuedEvent(BaseModel):
    typename__: Literal["RunEnqueuedEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsRunDequeuedEvent(BaseModel):
    typename__: Literal["RunDequeuedEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsRunStartingEvent(BaseModel):
    typename__: Literal["RunStartingEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsRunCancelingEvent(BaseModel):
    typename__: Literal["RunCancelingEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsRunCanceledEvent(BaseModel):
    typename__: Literal["RunCanceledEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsRunSuccessEvent(BaseModel):
    typename__: Literal["RunSuccessEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsStepWorkerStartedEvent(
    BaseModel
):
    typename__: Literal["StepWorkerStartedEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsStepWorkerStartingEvent(
    BaseModel
):
    typename__: Literal["StepWorkerStartingEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsHandledOutputEvent(BaseModel):
    typename__: Literal["HandledOutputEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsLoadedInputEvent(BaseModel):
    typename__: Literal["LoadedInputEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsLogsCapturedEvent(BaseModel):
    typename__: Literal["LogsCapturedEvent"] = Field(alias="__typename")
    file_key: str = Field(alias="fileKey")
    step_keys: Optional[List[str]] = Field(alias="stepKeys")
    external_stdout_url: Optional[str] = Field(alias="externalStdoutUrl")
    external_stderr_url: Optional[str] = Field(alias="externalStderrUrl")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsObjectStoreOperationEvent(
    BaseModel
):
    typename__: Literal["ObjectStoreOperationEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsStepExpectationResultEvent(
    BaseModel
):
    typename__: Literal["StepExpectationResultEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsMaterializationEvent(
    BaseModel
):
    typename__: Literal["MaterializationEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsObservationEvent(BaseModel):
    typename__: Literal["ObservationEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsFailedToMaterializeEvent(
    BaseModel
):
    typename__: Literal["FailedToMaterializeEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsEngineEvent(BaseModel):
    typename__: Literal["EngineEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsHookCompletedEvent(BaseModel):
    typename__: Literal["HookCompletedEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsHookSkippedEvent(BaseModel):
    typename__: Literal["HookSkippedEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsHookErroredEvent(BaseModel):
    typename__: Literal["HookErroredEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsAlertStartEvent(BaseModel):
    typename__: Literal["AlertStartEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsAlertSuccessEvent(BaseModel):
    typename__: Literal["AlertSuccessEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsAlertFailureEvent(BaseModel):
    typename__: Literal["AlertFailureEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsAssetMaterializationPlannedEvent(
    BaseModel
):
    typename__: Literal["AssetMaterializationPlannedEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsAssetCheckEvaluationPlannedEvent(
    BaseModel
):
    typename__: Literal["AssetCheckEvaluationPlannedEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunEventConnectionEventsAssetCheckEvaluationEvent(
    BaseModel
):
    typename__: Literal["AssetCheckEvaluationEvent"] = Field(alias="__typename")


class GetLogsCapturedEventsLogsForRunRunNotFoundError(BaseModel):
    typename__: Literal["RunNotFoundError"] = Field(alias="__typename")
    message: str


class GetLogsCapturedEventsLogsForRunPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str


GetLogsCapturedEvents.model_rebuild()
GetLogsCapturedEventsLogsForRunEventConnection.model_rebuild()
