# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from pydantic import Field

from .base_model import BaseModel
from .enums import ReportingTimeRange


class GetMetricsTimeRanges(BaseModel):
    metrics_time_ranges: "GetMetricsTimeRangesMetricsTimeRanges" = Field(
        alias="metricsTimeRanges"
    )


class GetMetricsTimeRangesMetricsTimeRanges(BaseModel):
    time_ranges: list[ReportingTimeRange] = Field(alias="timeRanges")


GetMetricsTimeRanges.model_rebuild()
