# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel


class GetAssetLocation(BaseModel):
    asset_node_or_error: Union[
        "GetAssetLocationAssetNodeOrErrorAssetNode",
        "GetAssetLocationAssetNodeOrErrorAssetNotFoundError",
    ] = Field(alias="assetNodeOrError", discriminator="typename__")


class GetAssetLocationAssetNodeOrErrorAssetNode(BaseModel):
    typename__: Literal["AssetNode"] = Field(alias="__typename")
    asset_key: "GetAssetLocationAssetNodeOrErrorAssetNodeAssetKey" = Field(
        alias="assetKey"
    )
    repository: "GetAssetLocationAssetNodeOrErrorAssetNodeRepository"


class GetAssetLocationAssetNodeOrErrorAssetNodeAssetKey(BaseModel):
    path: list[str]


class GetAssetLocationAssetNodeOrErrorAssetNodeRepository(BaseModel):
    name: str
    location: "GetAssetLocationAssetNodeOrErrorAssetNodeRepositoryLocation"


class GetAssetLocationAssetNodeOrErrorAssetNodeRepositoryLocation(BaseModel):
    name: str


class GetAssetLocationAssetNodeOrErrorAssetNotFoundError(BaseModel):
    typename__: Literal["AssetNotFoundError"] = Field(alias="__typename")
    message: str


GetAssetLocation.model_rebuild()
GetAssetLocationAssetNodeOrErrorAssetNode.model_rebuild()
GetAssetLocationAssetNodeOrErrorAssetNodeRepository.model_rebuild()
