# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class GetAssetPartitionStatus(BaseModel):
    asset_node_or_error: Union[
        "GetAssetPartitionStatusAssetNodeOrErrorAssetNode",
        "GetAssetPartitionStatusAssetNodeOrErrorAssetNotFoundError",
    ] = Field(alias="assetNodeOrError", discriminator="typename__")


class GetAssetPartitionStatusAssetNodeOrErrorAssetNode(BaseModel):
    typename__: Literal["AssetNode"] = Field(alias="__typename")
    partition_stats: Optional[
        "GetAssetPartitionStatusAssetNodeOrErrorAssetNodePartitionStats"
    ] = Field(alias="partitionStats")


class GetAssetPartitionStatusAssetNodeOrErrorAssetNodePartitionStats(BaseModel):
    num_materialized: int = Field(alias="numMaterialized")
    num_partitions: int = Field(alias="numPartitions")
    num_failed: int = Field(alias="numFailed")
    num_materializing: int = Field(alias="numMaterializing")


class GetAssetPartitionStatusAssetNodeOrErrorAssetNotFoundError(BaseModel):
    typename__: Literal["AssetNotFoundError"] = Field(alias="__typename")
    message: str


GetAssetPartitionStatus.model_rebuild()
GetAssetPartitionStatusAssetNodeOrErrorAssetNode.model_rebuild()
