# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import RunStatus


class GetRun(BaseModel):
    run_or_error: Union[
        "GetRunRunOrErrorRun",
        "GetRunRunOrErrorRunNotFoundError",
        "GetRunRunOrErrorPythonError",
    ] = Field(alias="runOrError", discriminator="typename__")


class GetRunRunOrErrorRun(BaseModel):
    typename__: Literal["Run"] = Field(alias="__typename")
    run_id: str = Field(alias="runId")
    status: RunStatus
    creation_time: float = Field(alias="creationTime")
    start_time: Optional[float] = Field(alias="startTime")
    end_time: Optional[float] = Field(alias="endTime")
    job_name: str = Field(alias="jobName")
    run_config_yaml: str = Field(alias="runConfigYaml")
    tags: list["GetRunRunOrErrorRunTags"]
    stats: Union[
        "GetRunRunOrErrorRunStatsRunStatsSnapshot",
        "GetRunRunOrErrorRunStatsPythonError",
    ] = Field(discriminator="typename__")


class GetRunRunOrErrorRunTags(BaseModel):
    key: str
    value: str


class GetRunRunOrErrorRunStatsRunStatsSnapshot(BaseModel):
    typename__: Literal["RunStatsSnapshot"] = Field(alias="__typename")
    steps_succeeded: int = Field(alias="stepsSucceeded")
    steps_failed: int = Field(alias="stepsFailed")
    materializations: int
    expectations: int


class GetRunRunOrErrorRunStatsPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")


class GetRunRunOrErrorRunNotFoundError(BaseModel):
    typename__: Literal["RunNotFoundError"] = Field(alias="__typename")
    run_id: str = Field(alias="runId")
    message: str


class GetRunRunOrErrorPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str
    stack: list[str]


GetRun.model_rebuild()
GetRunRunOrErrorRun.model_rebuild()
