# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import InstigationStatus


class GetSchedule(BaseModel):
    schedule_or_error: Union[
        "GetScheduleScheduleOrErrorSchedule",
        "GetScheduleScheduleOrErrorScheduleNotFoundError",
        "GetScheduleScheduleOrErrorPythonError",
    ] = Field(alias="scheduleOrError", discriminator="typename__")


class GetScheduleScheduleOrErrorSchedule(BaseModel):
    typename__: Literal["Schedule"] = Field(alias="__typename")
    id: str
    name: str
    cron_schedule: str = Field(alias="cronSchedule")
    pipeline_name: str = Field(alias="pipelineName")
    description: Optional[str]
    execution_timezone: Optional[str] = Field(alias="executionTimezone")
    schedule_state: "GetScheduleScheduleOrErrorScheduleScheduleState" = Field(
        alias="scheduleState"
    )


class GetScheduleScheduleOrErrorScheduleScheduleState(BaseModel):
    status: InstigationStatus


class GetScheduleScheduleOrErrorScheduleNotFoundError(BaseModel):
    typename__: Literal["ScheduleNotFoundError"] = Field(alias="__typename")
    message: str


class GetScheduleScheduleOrErrorPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str


GetSchedule.model_rebuild()
GetScheduleScheduleOrErrorSchedule.model_rebuild()
