# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class GetOrganizationSettings(BaseModel):
    organization_settings: Optional["GetOrganizationSettingsOrganizationSettings"] = (
        Field(alias="organizationSettings")
    )


class GetOrganizationSettingsOrganizationSettings(BaseModel):
    settings: Optional[Any]


GetOrganizationSettings.model_rebuild()
