# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetCapturedLogs(BaseModel):
    captured_logs: "GetCapturedLogsCapturedLogs" = Field(alias="capturedLogs")


class GetCapturedLogsCapturedLogs(BaseModel):
    stdout: Optional[str]
    stderr: Optional[str]
    cursor: Optional[str]


GetCapturedLogs.model_rebuild()
