# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Annotated, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class GetAssetMaterializationEvents(BaseModel):
    assets_or_error: Union[
        "GetAssetMaterializationEventsAssetsOrErrorAssetConnection",
        "GetAssetMaterializationEventsAssetsOrErrorPythonError",
    ] = Field(alias="assetsOrError", discriminator="typename__")


class GetAssetMaterializationEventsAssetsOrErrorAssetConnection(BaseModel):
    typename__: Literal["AssetConnection"] = Field(alias="__typename")
    nodes: List["GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodes"]


class GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodes(BaseModel):
    key: "GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesKey"
    asset_materializations: List[
        "GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializations"
    ] = Field(alias="assetMaterializations")


class GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesKey(BaseModel):
    path: List[str]


class GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializations(
    BaseModel
):
    timestamp: str
    run_id: str = Field(alias="runId")
    partition: Optional[str]
    tags: List[
        "GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsTags"
    ]
    metadata_entries: List[
        Annotated[
            Union[
                "GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesMetadataEntry",
                "GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesBoolMetadataEntry",
                "GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesFloatMetadataEntry",
                "GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesIntMetadataEntry",
                "GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesJsonMetadataEntry",
                "GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesMarkdownMetadataEntry",
                "GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesPathMetadataEntry",
                "GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesPythonArtifactMetadataEntry",
                "GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesTextMetadataEntry",
                "GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesUrlMetadataEntry",
            ],
            Field(discriminator="typename__"),
        ]
    ] = Field(alias="metadataEntries")


class GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsTags(
    BaseModel
):
    key: str
    value: str


class GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesMetadataEntry(
    BaseModel
):
    typename__: Literal[
        "AssetMetadataEntry",
        "CodeReferencesMetadataEntry",
        "JobMetadataEntry",
        "MetadataEntry",
        "NotebookMetadataEntry",
        "NullMetadataEntry",
        "PipelineRunMetadataEntry",
        "PoolMetadataEntry",
        "TableColumnLineageMetadataEntry",
        "TableMetadataEntry",
        "TableSchemaMetadataEntry",
        "TimestampMetadataEntry",
    ] = Field(alias="__typename")
    label: str
    description: Optional[str]


class GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesBoolMetadataEntry(
    BaseModel
):
    typename__: Literal["BoolMetadataEntry"] = Field(alias="__typename")
    label: str
    description: Optional[str]
    bool_value: Optional[bool] = Field(alias="boolValue")


class GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesFloatMetadataEntry(
    BaseModel
):
    typename__: Literal["FloatMetadataEntry"] = Field(alias="__typename")
    label: str
    description: Optional[str]
    float_value: Optional[float] = Field(alias="floatValue")


class GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesIntMetadataEntry(
    BaseModel
):
    typename__: Literal["IntMetadataEntry"] = Field(alias="__typename")
    label: str
    description: Optional[str]
    int_value: Optional[int] = Field(alias="intValue")


class GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesJsonMetadataEntry(
    BaseModel
):
    typename__: Literal["JsonMetadataEntry"] = Field(alias="__typename")
    label: str
    description: Optional[str]
    json_string: str = Field(alias="jsonString")


class GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesMarkdownMetadataEntry(
    BaseModel
):
    typename__: Literal["MarkdownMetadataEntry"] = Field(alias="__typename")
    label: str
    description: Optional[str]
    md_str: str = Field(alias="mdStr")


class GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesPathMetadataEntry(
    BaseModel
):
    typename__: Literal["PathMetadataEntry"] = Field(alias="__typename")
    label: str
    description: Optional[str]
    path: str


class GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesPythonArtifactMetadataEntry(
    BaseModel
):
    typename__: Literal["PythonArtifactMetadataEntry"] = Field(alias="__typename")
    label: str
    description: Optional[str]
    module: str
    name: str


class GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesTextMetadataEntry(
    BaseModel
):
    typename__: Literal["TextMetadataEntry"] = Field(alias="__typename")
    label: str
    description: Optional[str]
    text: str


class GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializationsMetadataEntriesUrlMetadataEntry(
    BaseModel
):
    typename__: Literal["UrlMetadataEntry"] = Field(alias="__typename")
    label: str
    description: Optional[str]
    url: str


class GetAssetMaterializationEventsAssetsOrErrorPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str


GetAssetMaterializationEvents.model_rebuild()
GetAssetMaterializationEventsAssetsOrErrorAssetConnection.model_rebuild()
GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodes.model_rebuild()
GetAssetMaterializationEventsAssetsOrErrorAssetConnectionNodesAssetMaterializations.model_rebuild()
