# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AgentStatus


class ListAgents(BaseModel):
    agents: list["ListAgentsAgents"]


class ListAgentsAgents(BaseModel):
    id: str
    agent_label: Optional[str] = Field(alias="agentLabel")
    status: AgentStatus
    last_heartbeat_time: float = Field(alias="lastHeartbeatTime")
    metadata: list["ListAgentsAgentsMetadata"]


class ListAgentsAgentsMetadata(BaseModel):
    key: str
    value: Optional[str]


ListAgents.model_rebuild()
ListAgentsAgents.model_rebuild()
