# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import AssetCheckCanExecuteIndividually


class ListAssetChecks(BaseModel):
    asset_node_or_error: Union[
        "ListAssetChecksAssetNodeOrErrorAssetNode",
        "ListAssetChecksAssetNodeOrErrorAssetNotFoundError",
    ] = Field(alias="assetNodeOrError", discriminator="typename__")


class ListAssetChecksAssetNodeOrErrorAssetNode(BaseModel):
    typename__: Literal["AssetNode"] = Field(alias="__typename")
    asset_checks_or_error: Union[
        "ListAssetChecksAssetNodeOrErrorAssetNodeAssetChecksOrErrorAssetChecks",
        "ListAssetChecksAssetNodeOrErrorAssetNodeAssetChecksOrErrorAssetCheckNeedsMigrationError",
        "ListAssetChecksAssetNodeOrErrorAssetNodeAssetChecksOrErrorAssetCheckNeedsUserCodeUpgrade",
        "ListAssetChecksAssetNodeOrErrorAssetNodeAssetChecksOrErrorAssetCheckNeedsAgentUpgradeError",
    ] = Field(alias="assetChecksOrError", discriminator="typename__")


class ListAssetChecksAssetNodeOrErrorAssetNodeAssetChecksOrErrorAssetChecks(BaseModel):
    typename__: Literal["AssetChecks"] = Field(alias="__typename")
    checks: List[
        "ListAssetChecksAssetNodeOrErrorAssetNodeAssetChecksOrErrorAssetChecksChecks"
    ]


class ListAssetChecksAssetNodeOrErrorAssetNodeAssetChecksOrErrorAssetChecksChecks(
    BaseModel
):
    name: str
    description: Optional[str]
    blocking: bool
    job_names: List[str] = Field(alias="jobNames")
    can_execute_individually: AssetCheckCanExecuteIndividually = Field(
        alias="canExecuteIndividually"
    )
    asset_key: (
        "ListAssetChecksAssetNodeOrErrorAssetNodeAssetChecksOrErrorAssetChecksChecksAssetKey"
    ) = Field(alias="assetKey")


class ListAssetChecksAssetNodeOrErrorAssetNodeAssetChecksOrErrorAssetChecksChecksAssetKey(
    BaseModel
):
    path: List[str]


class ListAssetChecksAssetNodeOrErrorAssetNodeAssetChecksOrErrorAssetCheckNeedsMigrationError(
    BaseModel
):
    typename__: Literal["AssetCheckNeedsMigrationError"] = Field(alias="__typename")
    message: str


class ListAssetChecksAssetNodeOrErrorAssetNodeAssetChecksOrErrorAssetCheckNeedsUserCodeUpgrade(
    BaseModel
):
    typename__: Literal["AssetCheckNeedsUserCodeUpgrade"] = Field(alias="__typename")
    message: str


class ListAssetChecksAssetNodeOrErrorAssetNodeAssetChecksOrErrorAssetCheckNeedsAgentUpgradeError(
    BaseModel
):
    typename__: Literal["AssetCheckNeedsAgentUpgradeError"] = Field(alias="__typename")
    message: str


class ListAssetChecksAssetNodeOrErrorAssetNotFoundError(BaseModel):
    typename__: Literal["AssetNotFoundError"] = Field(alias="__typename")
    message: str


ListAssetChecks.model_rebuild()
ListAssetChecksAssetNodeOrErrorAssetNode.model_rebuild()
ListAssetChecksAssetNodeOrErrorAssetNodeAssetChecksOrErrorAssetChecks.model_rebuild()
ListAssetChecksAssetNodeOrErrorAssetNodeAssetChecksOrErrorAssetChecksChecks.model_rebuild()
