# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import InstigationStatus


class ListRepositoriesWithSchedules(BaseModel):
    repositories_or_error: Union[
        "ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryConnection",
        "ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryNotFoundError",
        "ListRepositoriesWithSchedulesRepositoriesOrErrorPythonError",
    ] = Field(alias="repositoriesOrError", discriminator="typename__")


class ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryConnection(BaseModel):
    typename__: Literal["RepositoryConnection"] = Field(alias="__typename")
    nodes: List[
        "ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryConnectionNodes"
    ]


class ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryConnectionNodes(
    BaseModel
):
    name: str
    location: "ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryConnectionNodesLocation"
    schedules: List[
        "ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryConnectionNodesSchedules"
    ]


class ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryConnectionNodesLocation(
    BaseModel
):
    name: str


class ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryConnectionNodesSchedules(
    BaseModel
):
    id: str
    name: str
    cron_schedule: str = Field(alias="cronSchedule")
    pipeline_name: str = Field(alias="pipelineName")
    description: Optional[str]
    execution_timezone: Optional[str] = Field(alias="executionTimezone")
    schedule_state: (
        "ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryConnectionNodesSchedulesScheduleState"
    ) = Field(alias="scheduleState")


class ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryConnectionNodesSchedulesScheduleState(
    BaseModel
):
    status: InstigationStatus


class ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryNotFoundError(
    BaseModel
):
    typename__: Literal["RepositoryNotFoundError"] = Field(alias="__typename")
    message: str


class ListRepositoriesWithSchedulesRepositoriesOrErrorPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str


ListRepositoriesWithSchedules.model_rebuild()
ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryConnection.model_rebuild()
ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryConnectionNodes.model_rebuild()
ListRepositoriesWithSchedulesRepositoriesOrErrorRepositoryConnectionNodesSchedules.model_rebuild()
