# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class ListCodeLocations(BaseModel):
    workspace: Optional["ListCodeLocationsWorkspace"]


class ListCodeLocationsWorkspace(BaseModel):
    workspace_entries: List["ListCodeLocationsWorkspaceWorkspaceEntries"] = Field(
        alias="workspaceEntries"
    )


class ListCodeLocationsWorkspaceWorkspaceEntries(BaseModel):
    location_name: str = Field(alias="locationName")
    serialized_deployment_metadata: str = Field(alias="serializedDeploymentMetadata")


ListCodeLocations.model_rebuild()
ListCodeLocationsWorkspace.model_rebuild()
