# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import List, Literal, Union

from pydantic import Field

from .base_model import BaseModel


class ListRepositoriesForTicks(BaseModel):
    repositories_or_error: Union[
        "ListRepositoriesForTicksRepositoriesOrErrorRepositoryConnection",
        "ListRepositoriesForTicksRepositoriesOrErrorRepositoryNotFoundError",
        "ListRepositoriesForTicksRepositoriesOrErrorPythonError",
    ] = Field(alias="repositoriesOrError", discriminator="typename__")


class ListRepositoriesForTicksRepositoriesOrErrorRepositoryConnection(BaseModel):
    typename__: Literal["RepositoryConnection"] = Field(alias="__typename")
    nodes: List["ListRepositoriesForTicksRepositoriesOrErrorRepositoryConnectionNodes"]


class ListRepositoriesForTicksRepositoriesOrErrorRepositoryConnectionNodes(BaseModel):
    name: str
    location: (
        "ListRepositoriesForTicksRepositoriesOrErrorRepositoryConnectionNodesLocation"
    )
    sensors: List[
        "ListRepositoriesForTicksRepositoriesOrErrorRepositoryConnectionNodesSensors"
    ]
    schedules: List[
        "ListRepositoriesForTicksRepositoriesOrErrorRepositoryConnectionNodesSchedules"
    ]


class ListRepositoriesForTicksRepositoriesOrErrorRepositoryConnectionNodesLocation(
    BaseModel
):
    name: str


class ListRepositoriesForTicksRepositoriesOrErrorRepositoryConnectionNodesSensors(
    BaseModel
):
    name: str


class ListRepositoriesForTicksRepositoriesOrErrorRepositoryConnectionNodesSchedules(
    BaseModel
):
    name: str


class ListRepositoriesForTicksRepositoriesOrErrorRepositoryNotFoundError(BaseModel):
    typename__: Literal["RepositoryNotFoundError"] = Field(alias="__typename")
    message: str


class ListRepositoriesForTicksRepositoriesOrErrorPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str


ListRepositoriesForTicks.model_rebuild()
ListRepositoriesForTicksRepositoriesOrErrorRepositoryConnection.model_rebuild()
ListRepositoriesForTicksRepositoriesOrErrorRepositoryConnectionNodes.model_rebuild()
