# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import ReportingUnitType


class ListSpecificAssetMetricTypes(BaseModel):
    metric_types_for_specific_asset: Union[
        "ListSpecificAssetMetricTypesMetricTypesForSpecificAssetMetricTypeList",
        "ListSpecificAssetMetricTypesMetricTypesForSpecificAssetUnauthorizedError",
        "ListSpecificAssetMetricTypesMetricTypesForSpecificAssetPythonError",
    ] = Field(alias="metricTypesForSpecificAsset", discriminator="typename__")


class ListSpecificAssetMetricTypesMetricTypesForSpecificAssetMetricTypeList(BaseModel):
    typename__: Literal["MetricTypeList"] = Field(alias="__typename")
    id: str
    metric_types: list[
        "ListSpecificAssetMetricTypesMetricTypesForSpecificAssetMetricTypeListMetricTypes"
    ] = Field(alias="metricTypes")


class ListSpecificAssetMetricTypesMetricTypesForSpecificAssetMetricTypeListMetricTypes(
    BaseModel
):
    id: str
    metric_name: str = Field(alias="metricName")
    display_name: str = Field(alias="displayName")
    category: Optional[str]
    unit_type: Optional[ReportingUnitType] = Field(alias="unitType")
    description: Optional[str]
    pending: Optional[bool]
    visible: Optional[bool]
    custom_icon: Optional[str] = Field(alias="customIcon")
    cost_multiplier: Optional[float] = Field(alias="costMultiplier")


class ListSpecificAssetMetricTypesMetricTypesForSpecificAssetUnauthorizedError(
    BaseModel
):
    typename__: Literal["UnauthorizedError"] = Field(alias="__typename")
    message: str


class ListSpecificAssetMetricTypesMetricTypesForSpecificAssetPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str
    stack: list[str]


ListSpecificAssetMetricTypes.model_rebuild()
ListSpecificAssetMetricTypesMetricTypesForSpecificAssetMetricTypeList.model_rebuild()
