# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import InstigationStatus, SensorType


class ListRepositoriesWithSensors(BaseModel):
    repositories_or_error: Union[
        "ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryConnection",
        "ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryNotFoundError",
        "ListRepositoriesWithSensorsRepositoriesOrErrorPythonError",
    ] = Field(alias="repositoriesOrError", discriminator="typename__")


class ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryConnection(BaseModel):
    typename__: Literal["RepositoryConnection"] = Field(alias="__typename")
    nodes: List[
        "ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryConnectionNodes"
    ]


class ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryConnectionNodes(
    BaseModel
):
    name: str
    location: "ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryConnectionNodesLocation"
    sensors: List[
        "ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryConnectionNodesSensors"
    ]


class ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryConnectionNodesLocation(
    BaseModel
):
    name: str


class ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryConnectionNodesSensors(
    BaseModel
):
    id: str
    name: str
    sensor_state: (
        "ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryConnectionNodesSensorsSensorState"
    ) = Field(alias="sensorState")
    sensor_type: SensorType = Field(alias="sensorType")
    description: Optional[str]


class ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryConnectionNodesSensorsSensorState(
    BaseModel
):
    status: InstigationStatus


class ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryNotFoundError(BaseModel):
    typename__: Literal["RepositoryNotFoundError"] = Field(alias="__typename")
    message: str


class ListRepositoriesWithSensorsRepositoriesOrErrorPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str


ListRepositoriesWithSensors.model_rebuild()
ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryConnection.model_rebuild()
ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryConnectionNodes.model_rebuild()
ListRepositoriesWithSensorsRepositoriesOrErrorRepositoryConnectionNodesSensors.model_rebuild()
