# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class ReconcileAlertPolicies(BaseModel):
    reconcile_alert_policies_from_document: Union[
        "ReconcileAlertPoliciesReconcileAlertPoliciesFromDocumentReconcileAlertPoliciesSuccess",
        "ReconcileAlertPoliciesReconcileAlertPoliciesFromDocumentPythonError",
        "ReconcileAlertPoliciesReconcileAlertPoliciesFromDocumentUnauthorizedError",
        "ReconcileAlertPoliciesReconcileAlertPoliciesFromDocumentInvalidAlertPolicyError",
    ] = Field(alias="reconcileAlertPoliciesFromDocument", discriminator="typename__")


class ReconcileAlertPoliciesReconcileAlertPoliciesFromDocumentReconcileAlertPoliciesSuccess(
    BaseModel
):
    typename__: Literal["ReconcileAlertPoliciesSuccess"] = Field(alias="__typename")
    alert_policies: List[
        Optional[
            "ReconcileAlertPoliciesReconcileAlertPoliciesFromDocumentReconcileAlertPoliciesSuccessAlertPolicies"
        ]
    ] = Field(alias="alertPolicies")


class ReconcileAlertPoliciesReconcileAlertPoliciesFromDocumentReconcileAlertPoliciesSuccessAlertPolicies(
    BaseModel
):
    name: str


class ReconcileAlertPoliciesReconcileAlertPoliciesFromDocumentPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str


class ReconcileAlertPoliciesReconcileAlertPoliciesFromDocumentUnauthorizedError(
    BaseModel
):
    typename__: Literal["UnauthorizedError"] = Field(alias="__typename")
    message: str


class ReconcileAlertPoliciesReconcileAlertPoliciesFromDocumentInvalidAlertPolicyError(
    BaseModel
):
    typename__: Literal["InvalidAlertPolicyError"] = Field(alias="__typename")
    message: str


ReconcileAlertPolicies.model_rebuild()
ReconcileAlertPoliciesReconcileAlertPoliciesFromDocumentReconcileAlertPoliciesSuccess.model_rebuild()
