# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import EvaluationErrorReason


class RerunBackfill(BaseModel):
    reexecute_partition_backfill: Union[
        "RerunBackfillReexecutePartitionBackfillLaunchBackfillSuccess",
        "RerunBackfillReexecutePartitionBackfillPartitionSetNotFoundError",
        "RerunBackfillReexecutePartitionBackfillPartitionKeysNotFoundError",
        "RerunBackfillReexecutePartitionBackfillInvalidStepError",
        "RerunBackfillReexecutePartitionBackfillInvalidOutputError",
        "RerunBackfillReexecutePartitionBackfillRunConfigValidationInvalid",
        "RerunBackfillReexecutePartitionBackfillPipelineNotFoundError",
        "RerunBackfillReexecutePartitionBackfillRunConflict",
        "RerunBackfillReexecutePartitionBackfillUnauthorizedError",
        "RerunBackfillReexecutePartitionBackfillPythonError",
        "RerunBackfillReexecutePartitionBackfillInvalidSubsetError",
        "RerunBackfillReexecutePartitionBackfillPresetNotFoundError",
        "RerunBackfillReexecutePartitionBackfillConflictingExecutionParamsError",
        "RerunBackfillReexecutePartitionBackfillNoModeProvidedError",
    ] = Field(alias="reexecutePartitionBackfill", discriminator="typename__")


class RerunBackfillReexecutePartitionBackfillLaunchBackfillSuccess(BaseModel):
    typename__: Literal["LaunchBackfillSuccess"] = Field(alias="__typename")
    backfill_id: str = Field(alias="backfillId")
    launched_run_ids: Optional[list[Optional[str]]] = Field(alias="launchedRunIds")


class RerunBackfillReexecutePartitionBackfillPartitionSetNotFoundError(BaseModel):
    typename__: Literal["PartitionSetNotFoundError"] = Field(alias="__typename")


class RerunBackfillReexecutePartitionBackfillPartitionKeysNotFoundError(BaseModel):
    typename__: Literal["PartitionKeysNotFoundError"] = Field(alias="__typename")


class RerunBackfillReexecutePartitionBackfillInvalidStepError(BaseModel):
    typename__: Literal["InvalidStepError"] = Field(alias="__typename")
    invalid_step_key: str = Field(alias="invalidStepKey")


class RerunBackfillReexecutePartitionBackfillInvalidOutputError(BaseModel):
    typename__: Literal["InvalidOutputError"] = Field(alias="__typename")
    step_key: str = Field(alias="stepKey")
    invalid_output_name: str = Field(alias="invalidOutputName")


class RerunBackfillReexecutePartitionBackfillRunConfigValidationInvalid(BaseModel):
    typename__: Literal["RunConfigValidationInvalid"] = Field(alias="__typename")
    errors: list[
        "RerunBackfillReexecutePartitionBackfillRunConfigValidationInvalidErrors"
    ]


class RerunBackfillReexecutePartitionBackfillRunConfigValidationInvalidErrors(
    BaseModel
):
    typename__: Literal[
        "FieldNotDefinedConfigError",
        "FieldsNotDefinedConfigError",
        "MissingFieldConfigError",
        "MissingFieldsConfigError",
        "PipelineConfigValidationError",
        "RuntimeMismatchConfigError",
        "SelectorTypeConfigError",
    ] = Field(alias="__typename")
    message: str
    reason: EvaluationErrorReason


class RerunBackfillReexecutePartitionBackfillPipelineNotFoundError(BaseModel):
    typename__: Literal["PipelineNotFoundError"] = Field(alias="__typename")
    pipeline_name: str = Field(alias="pipelineName")
    message: str


class RerunBackfillReexecutePartitionBackfillRunConflict(BaseModel):
    typename__: Literal["RunConflict"] = Field(alias="__typename")
    message: str


class RerunBackfillReexecutePartitionBackfillUnauthorizedError(BaseModel):
    typename__: Literal["UnauthorizedError"] = Field(alias="__typename")
    message: str


class RerunBackfillReexecutePartitionBackfillPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str
    stack: list[str]


class RerunBackfillReexecutePartitionBackfillInvalidSubsetError(BaseModel):
    typename__: Literal["InvalidSubsetError"] = Field(alias="__typename")
    message: str


class RerunBackfillReexecutePartitionBackfillPresetNotFoundError(BaseModel):
    typename__: Literal["PresetNotFoundError"] = Field(alias="__typename")


class RerunBackfillReexecutePartitionBackfillConflictingExecutionParamsError(BaseModel):
    typename__: Literal["ConflictingExecutionParamsError"] = Field(alias="__typename")


class RerunBackfillReexecutePartitionBackfillNoModeProvidedError(BaseModel):
    typename__: Literal["NoModeProvidedError"] = Field(alias="__typename")


RerunBackfill.model_rebuild()
RerunBackfillReexecutePartitionBackfillRunConfigValidationInvalid.model_rebuild()
