# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class SetDeploymentSettings(BaseModel):
    set_deployment_settings: Union[
        "SetDeploymentSettingsSetDeploymentSettingsDeploymentSettings",
        "SetDeploymentSettingsSetDeploymentSettingsDeploymentNotFoundError",
        "SetDeploymentSettingsSetDeploymentSettingsDuplicateDeploymentError",
        "SetDeploymentSettingsSetDeploymentSettingsDeleteFinalDeploymentError",
        "SetDeploymentSettingsSetDeploymentSettingsUnauthorizedError",
        "SetDeploymentSettingsSetDeploymentSettingsPythonError",
    ] = Field(alias="setDeploymentSettings", discriminator="typename__")


class SetDeploymentSettingsSetDeploymentSettingsDeploymentSettings(BaseModel):
    typename__: Literal["DeploymentSettings"] = Field(alias="__typename")
    settings: Optional[Any]


class SetDeploymentSettingsSetDeploymentSettingsDeploymentNotFoundError(BaseModel):
    typename__: Literal["DeploymentNotFoundError"] = Field(alias="__typename")


class SetDeploymentSettingsSetDeploymentSettingsDuplicateDeploymentError(BaseModel):
    typename__: Literal["DuplicateDeploymentError"] = Field(alias="__typename")


class SetDeploymentSettingsSetDeploymentSettingsDeleteFinalDeploymentError(BaseModel):
    typename__: Literal["DeleteFinalDeploymentError"] = Field(alias="__typename")


class SetDeploymentSettingsSetDeploymentSettingsUnauthorizedError(BaseModel):
    typename__: Literal["UnauthorizedError"] = Field(alias="__typename")
    message: str


class SetDeploymentSettingsSetDeploymentSettingsPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str


SetDeploymentSettings.model_rebuild()
