# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class UpdateOrganizationSettings(BaseModel):
    set_organization_settings: Union[
        "UpdateOrganizationSettingsSetOrganizationSettingsOrganizationSettings",
        "UpdateOrganizationSettingsSetOrganizationSettingsUnauthorizedError",
        "UpdateOrganizationSettingsSetOrganizationSettingsPythonError",
    ] = Field(alias="setOrganizationSettings", discriminator="typename__")


class UpdateOrganizationSettingsSetOrganizationSettingsOrganizationSettings(BaseModel):
    typename__: Literal["OrganizationSettings"] = Field(alias="__typename")
    settings: Optional[Any]


class UpdateOrganizationSettingsSetOrganizationSettingsUnauthorizedError(BaseModel):
    typename__: Literal["UnauthorizedError"] = Field(alias="__typename")
    message: str


class UpdateOrganizationSettingsSetOrganizationSettingsPythonError(BaseModel):
    typename__: Literal["PythonError"] = Field(alias="__typename")
    message: str


UpdateOrganizationSettings.model_rebuild()
