dagsterCloud:
  deployment: "staging"
  agentTokenSecretName: dagster-cloud-agent-token
  branchDeployments: false

workspace:
  serverTTL:
    fullDeployments:
      enabled: true
      ttlSeconds: 14400
  envSecrets:
    - name: dagster-staging-env
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
  runK8sConfig:
    podSpecConfig:
      nodeSelector:
        cloud.google.com/gke-nodepool: "staging-pool"

dagsterCloudAgent:
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

serviceAccount:
  create: true
  name: dagster-agent-staging
  annotations: {}
