def types():
    from dagster_graphql.schema.roots.assets import (
        GrapheneAssetConnection,
        GrapheneAssetOrError,
        GrapheneAssetsOrError,
    )
    from dagster_graphql.schema.roots.execution_plan import GrapheneExecutionPlanOrError
    from dagster_graphql.schema.roots.mutation import (
        GrapheneDeletePipelineRunResult,
        GrapheneDeletePipelineRunSuccess,
        GrapheneDeleteRunMutation,
        GrapheneLaunchBackfillMutation,
        GrapheneLaunchMultipleRunsMutation,
        GrapheneLaunchRunMutation,
        GrapheneLaunchRunReexecutionMutation,
        GrapheneReloadRepositoryLocationMutation,
        GrapheneReloadRepositoryLocationMutationResult,
        GrapheneReloadWorkspaceMutation,
        GrapheneReloadWorkspaceMutationResult,
        GrapheneShutdownRepositoryLocationMutation,
        GrapheneShutdownRepositoryLocationMutationResult,
        GrapheneTerminatePipelineExecutionFailure,
        GrapheneTerminatePipelineExecutionSuccess,
        GrapheneTerminateRunFailure,
        GrapheneTerminateRunMutation,
        GrapheneTerminateRunPolicy,
        GrapheneTerminateRunResult,
        GrapheneTerminateRunSuccess,
    )
    from dagster_graphql.schema.roots.pipeline import GraphenePipelineOrError

    return [
        GrapheneAssetConnection,
        GrapheneAssetOrError,
        GrapheneAssetsOrError,
        GrapheneDeletePipelineRunResult,
        GrapheneDeletePipelineRunSuccess,
        GrapheneDeleteRunMutation,
        GrapheneExecutionPlanOrError,
        GrapheneLaunchBackfillMutation,
        GrapheneLaunchRunMutation,
        GrapheneLaunchMultipleRunsMutation,
        GrapheneLaunchRunReexecutionMutation,
        GraphenePipelineOrError,
        GrapheneReloadRepositoryLocationMutation,
        GrapheneReloadRepositoryLocationMutationResult,
        GrapheneReloadWorkspaceMutation,
        GrapheneReloadWorkspaceMutationResult,
        GrapheneShutdownRepositoryLocationMutation,
        GrapheneShutdownRepositoryLocationMutationResult,
        GrapheneTerminatePipelineExecutionFailure,
        GrapheneTerminatePipelineExecutionSuccess,
        GrapheneTerminateRunFailure,
        GrapheneTerminateRunMutation,
        GrapheneTerminateRunResult,
        GrapheneTerminateRunSuccess,
        GrapheneTerminateRunPolicy,
    ]
