[tox]
skipsdist = true

[testenv]
download = True
passenv =
    CI_PULL_REQUEST
    BUILDKITE*
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
allowlist_externals =
  /bin/bash
  /usr/bin/env
commands =
  !windows: /usr/bin/env bash -c '! pip list --exclude-editable | grep -e dagster'
  pytest -vv {posargs}
