[tox]
requires =
    tox-uv>=1.16
skipsdist = True

[testenv]
runner = uv-venv-lock-runner
uv_sync_locked = false
uv_sync_flags = --frozen
download = True
passenv =
    CI_*
    BUILDKITE*
    BACKCOMPAT_TESTS_WEBSERVER_HOST
    EARLIEST_TESTED_RELEASE
    PYTEST_ADDOPTS
    PYTEST_PLUGINS

dependency_groups =
    test

allowlist_externals =
  /bin/bash
  uv
commands =
  !windows: /bin/bash -c '! uv pip list --exclude-editable | grep -e dagster'
  user-code-latest-release: pytest -m "user-code-latest-release" -vv -s {posargs}
  user-code-earliest-release: pytest -m "user-code-earliest-release" -vv -s {posargs}
