hello_world:
	dagster pipeline execute -f test_intro_tutorial_part_one.py  -n define_pipeline

part_two:
	dagster pipeline execute -f test_intro_tutorial_part_two.py -n define_pipeline

part_three:
	dagster pipeline execute -f test_intro_tutorial_part_three.py -n define_pipeline

part_four:
	dagster pipeline execute -f test_intro_tutorial_part_four.py -n define_pipeline

part_five_step_one:
	dagster pipeline execute -f test_intro_tutorial_part_five.py -n define_step_one_pipeline 

part_five_step_two:
	dagster pipeline execute -f test_intro_tutorial_part_five.py -n define_step_two_pipeline 
