[tox]
requires =
    tox-uv>=1.16
envlist =
  py312-default
  py312-pex_tests
  py313-default
  py313-pex_tests
  py314-default
  py314-pex_tests
skipsdist = True

[testenv]
runner = uv-venv-lock-runner
uv_sync_locked = false
uv_sync_flags = --frozen
download = True
setenv =
  DD_DOGSTATSD_DISABLE = true
passenv =
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
    CI_*
    BUILDKITE*
    DAGSTER_GIT_REPO_DIR
    DAGSTER_INTERNAL_GIT_REPO_DIR
    SNOWFLAKE*
    AWS_*
    DOCKER_CONFIG
dependency_groups =
    test
allowlist_externals =
  /bin/bash
  uv
commands =
  /bin/bash -c '! uv pip list --exclude-editable | grep -e dagster'
  default: pytest -vv \
    --ignore ./dagster_cloud_tests/cli_tests/pex_tests \
    --durations 10 {posargs}
  pex_tests: pytest -vv ./dagster_cloud_tests/cli_tests/pex_tests --durations 10 {posargs} --timeout 900
