FROM python:3.10-slim

# install pipes
RUN pip install pandas numpy
RUN pip install dagster-pipes>=1.5.1

WORKDIR /app
COPY pipes/join_iot.py /app/join_iot.py
RUN chmod +x /app/join_iot.py

# Run pipes.py when the container launches
ENTRYPOINT ["python", "/app/join_iot.py"]