LAZY_LOAD = {
    ".config": ("ConfigMapping",),
    ".decorators": (
        "asset_sensor",
        "composite_solid",
        "config_mapping",
        "daily_schedule",
        "failure_hook",
        "graph",
        "hook",
        "hourly_schedule",
        "job",
        "lambda_solid",
        "monthly_schedule",
        "op",
        "pipeline",
        "repository",
        "schedule",
        "sensor",
        "solid",
        "success_hook",
        "weekly_schedule",
    ),
    ".dependency": (
        "DependencyDefinition",
        "MultiDependencyDefinition",
        "Node",
        "NodeHandle",
        "NodeInvocation",
        "SolidInputHandle",
        "SolidInvocation",
        "SolidOutputHandle",
    ),
    ".events": (
        "AssetKey",
        "AssetMaterialization",
        "AssetObservation",
        "DynamicOutput",
        "ExpectationResult",
        "Failure",
        "HookExecutionResult",
        "Materialization",
        "Output",
        "RetryRequested",
        "TypeCheck",
    ),
    ".executor_definition": (
        "ExecutorDefinition",
        "ExecutorRequirement",
        "default_executors",
        "executor",
        "in_process_executor",
        "multiple_process_executor_requirements",
        "multiprocess_executor",
    ),
    ".graph_definition": ("GraphDefinition",),
    ".hook_definition": ("HookDefinition",),
    ".input": ("GraphIn", "In", "InputDefinition", "InputMapping",),
    ".job_definition": ("JobDefinition",),
    ".logger_definition": ("LoggerDefinition", "build_init_logger_context", "logger",),
    ".metadata": (
        "DagsterAssetMetadataValue",
        "DagsterPipelineRunMetadataValue",
        "FloatMetadataValue",
        "IntMetadataValue",
        "JsonMetadataValue",
        "MarkdownMetadataValue",
        "MetadataEntry",
        "MetadataValue",
        "PathMetadataValue",
        "PythonArtifactMetadataValue",
        "TableColumn",
        "TableColumnConstraints",
        "TableConstraints",
        "TableMetadataValue",
        "TableRecord",
        "TableSchema",
        "TableSchemaMetadataValue",
        "TextMetadataValue",
        "UrlMetadataValue",
    ),
    ".mode": ("ModeDefinition",),
    ".op_definition": ("OpDefinition",),
    ".output": (
        "DynamicOut",
        "DynamicOutputDefinition",
        "GraphOut",
        "Out",
        "OutputDefinition",
        "OutputMapping",
    ),
    ".partition": (
        "DynamicPartitionsDefinition",
        "Partition",
        "PartitionScheduleDefinition",
        "PartitionSetDefinition",
        "PartitionedConfig",
        "PartitionsDefinition",
        "StaticPartitionsDefinition",
        "dynamic_partitioned_config",
        "static_partitioned_config",
    ),
    ".partitioned_schedule": ("build_schedule_from_partitioned_job", "schedule_from_partitions",),
    ".pipeline_base": ("IPipeline",),
    ".pipeline_definition": ("PipelineDefinition",),
    ".preset": ("PresetDefinition",),
    ".reconstructable": (
        "ReconstructablePipeline",
        "build_reconstructable_pipeline",
        "reconstructable",
    ),
    ".repository_definition": ("RepositoryData", "RepositoryDefinition",),
    ".resource_definition": ("ResourceDefinition", "make_values_resource", "resource",),
    ".run_config_schema": ("RunConfigSchema", "create_run_config_schema",),
    ".run_request": ("InstigatorType", "RunRequest", "SkipReason",),
    ".run_status_sensor_definition": (
        "PipelineFailureSensorContext",
        "RunFailureSensorContext",
        "RunStatusSensorContext",
        "RunStatusSensorDefinition",
        "pipeline_failure_sensor",
        "run_failure_sensor",
        "run_status_sensor",
    ),
    ".schedule_definition": (
        "DefaultScheduleStatus",
        "ScheduleDefinition",
        "ScheduleEvaluationContext",
        "ScheduleExecutionContext",
    ),
    ".sensor_definition": (
        "AssetSensorDefinition",
        "DefaultSensorStatus",
        "SensorDefinition",
        "SensorEvaluationContext",
        "SensorExecutionContext",
    ),
    ".solid_container": ("create_execution_structure",),
    ".solid_definition": ("CompositeSolidDefinition", "NodeDefinition", "SolidDefinition",),
    ".time_window_partitions": (
        "DailyPartitionsDefinition",
        "HourlyPartitionsDefinition",
        "MonthlyPartitionsDefinition",
        "WeeklyPartitionsDefinition",
        "daily_partitioned_config",
        "hourly_partitioned_config",
        "monthly_partitioned_config",
        "weekly_partitioned_config",
    ),
}
