import {RunMetadataProviderMessageFragment} from '../../runs/types/RunMetadataProvider.types';
import {IGanttNode} from '../Constants';

export const GRAPH: IGanttNode[] = [
  {name: 'aop', inputs: [], outputs: [{dependedBy: [{solid: {name: 'bop'}}]}]},
  {name: 'cop', inputs: [{dependsOn: [{solid: {name: 'bop'}}]}], outputs: []},
  {
    name: 'bop',
    inputs: [{dependsOn: [{solid: {name: 'aop'}}]}],
    outputs: [{dependedBy: [{solid: {name: 'cop'}}]}],
  },
];

export const LOGS: RunMetadataProviderMessageFragment[] = [
  {
    message: '',
    timestamp: '1690126905471',
    stepKey: null,
    __typename: 'RunStartingEvent',
  },
  {
    message: 'Started process for run (pid: 65256).',
    timestamp: '1690126906220',
    stepKey: null,
    __typename: 'EngineEvent',
    markerStart: null,
    markerEnd: null,
  },
  {
    message: 'Started execution of run for "dynamic_graph".',
    timestamp: '1690126906451',
    stepKey: null,
    __typename: 'RunStartEvent',
  },
  {
    message: 'Executing steps using multiprocess executor: parent process (pid: 65256)',
    timestamp: '1690126906499',
    stepKey: null,
    __typename: 'EngineEvent',
    markerStart: null,
    markerEnd: null,
  },
  {
    message: 'Launching subprocess for "aop".',
    timestamp: '1690126906506',
    stepKey: 'aop',
    __typename: 'StepWorkerStartingEvent',
    markerStart: 'step_process_start',
    markerEnd: null,
  },
  {
    message: 'Executing step "aop" in subprocess.',
    timestamp: '1690126907234',
    stepKey: 'aop',
    __typename: 'StepWorkerStartedEvent',
    markerStart: null,
    markerEnd: 'step_process_start',
  },
  {
    message: 'Starting initialization of resources [io_manager].',
    timestamp: '1690126907258',
    stepKey: 'aop',
    __typename: 'ResourceInitStartedEvent',
    markerStart: 'resources',
    markerEnd: null,
  },
  {
    message: 'Finished initialization of resources [io_manager].',
    timestamp: '1690126907276',
    stepKey: 'aop',
    __typename: 'ResourceInitSuccessEvent',
    markerStart: null,
    markerEnd: 'resources',
  },
  {
    message: 'Started execution of step "aop".',
    timestamp: '1690126907319',
    stepKey: 'aop',
    __typename: 'ExecutionStepStartEvent',
  },
  {
    message: 'Execution of step "aop" failed and has requested a retry in 5 seconds.',
    timestamp: '1690126907330',
    stepKey: 'aop',
    __typename: 'ExecutionStepUpForRetryEvent',
  },
  {
    message: 'Launching subprocess for "aop".',
    timestamp: '1690126912342',
    stepKey: 'aop',
    __typename: 'StepWorkerStartingEvent',
    markerStart: 'step_process_start',
    markerEnd: null,
  },
  {
    message: 'Executing step "aop" in subprocess.',
    timestamp: '1690126913038',
    stepKey: 'aop',
    __typename: 'StepWorkerStartedEvent',
    markerStart: null,
    markerEnd: 'step_process_start',
  },
  {
    message: 'Starting initialization of resources [io_manager].',
    timestamp: '1690126913062',
    stepKey: 'aop',
    __typename: 'ResourceInitStartedEvent',
    markerStart: 'resources',
    markerEnd: null,
  },
  {
    message: 'Finished initialization of resources [io_manager].',
    timestamp: '1690126913084',
    stepKey: 'aop',
    __typename: 'ResourceInitSuccessEvent',
    markerStart: null,
    markerEnd: 'resources',
  },
  {
    message: 'Started re-execution (attempt # 2) of step "aop".',
    timestamp: '1690126913127',
    stepKey: 'aop',
    __typename: 'ExecutionStepRestartEvent',
  },
  {
    message: 'Execution of step "aop" failed and has requested a retry in 5 seconds.',
    timestamp: '1690126913137',
    stepKey: 'aop',
    __typename: 'ExecutionStepUpForRetryEvent',
  },
  {
    message: 'Launching subprocess for "aop".',
    timestamp: '1690126918146',
    stepKey: 'aop',
    __typename: 'StepWorkerStartingEvent',
    markerStart: 'step_process_start',
    markerEnd: null,
  },
  {
    message: 'Executing step "aop" in subprocess.',
    timestamp: '1690126918838',
    stepKey: 'aop',
    __typename: 'StepWorkerStartedEvent',
    markerStart: null,
    markerEnd: 'step_process_start',
  },
  {
    message: 'Starting initialization of resources [io_manager].',
    timestamp: '1690126918866',
    stepKey: 'aop',
    __typename: 'ResourceInitStartedEvent',
    markerStart: 'resources',
    markerEnd: null,
  },
  {
    message: 'Finished initialization of resources [io_manager].',
    timestamp: '1690126918882',
    stepKey: 'aop',
    __typename: 'ResourceInitSuccessEvent',
    markerStart: null,
    markerEnd: 'resources',
  },
  {
    message: 'Started re-execution (attempt # 3) of step "aop".',
    timestamp: '1690126918928',
    stepKey: 'aop',
    __typename: 'ExecutionStepRestartEvent',
  },
  {
    message: 'Execution of step "aop" failed and has requested a retry in 5 seconds.',
    timestamp: '1690126918938',
    stepKey: 'aop',
    __typename: 'ExecutionStepUpForRetryEvent',
  },
  {
    message: 'Launching subprocess for "aop".',
    timestamp: '1690126923948',
    stepKey: 'aop',
    __typename: 'StepWorkerStartingEvent',
    markerStart: 'step_process_start',
    markerEnd: null,
  },
  {
    message: 'Executing step "aop" in subprocess.',
    timestamp: '1690126924633',
    stepKey: 'aop',
    __typename: 'StepWorkerStartedEvent',
    markerStart: null,
    markerEnd: 'step_process_start',
  },
  {
    message: 'Starting initialization of resources [io_manager].',
    timestamp: '1690126924664',
    stepKey: 'aop',
    __typename: 'ResourceInitStartedEvent',
    markerStart: 'resources',
    markerEnd: null,
  },
  {
    message: 'Finished initialization of resources [io_manager].',
    timestamp: '1690126924686',
    stepKey: 'aop',
    __typename: 'ResourceInitSuccessEvent',
    markerStart: null,
    markerEnd: 'resources',
  },
  {
    message: 'Started re-execution (attempt # 4) of step "aop".',
    timestamp: '1690126924724',
    stepKey: 'aop',
    __typename: 'ExecutionStepRestartEvent',
  },
  {
    message: 'Execution of step "aop" failed.',
    timestamp: '1690126924734',
    stepKey: 'aop',
    __typename: 'ExecutionStepFailureEvent',
  },
  {
    message: "Dependencies for step bop failed: ['aop']. Not executing.",
    timestamp: '1690126924756',
    stepKey: 'bop',
    __typename: 'LogMessageEvent',
  },
  {
    message: "Dependencies for step cop were not executed: ['bop']. Not executing.",
    timestamp: '1690126924765',
    stepKey: 'cop',
    __typename: 'LogMessageEvent',
  },
  {
    message: 'Multiprocess executor: parent process exiting after 18.36s (pid: 65256)',
    timestamp: '1690126924865',
    stepKey: null,
    __typename: 'EngineEvent',
    markerStart: null,
    markerEnd: null,
  },
  {
    message: 'Execution of run for "dynamic_graph" failed. Steps failed: [\'aop\'].',
    timestamp: '1690126924895',
    stepKey: null,
    __typename: 'RunFailureEvent',
  },
  {
    message: 'Process for run exited (pid: 65256).',
    timestamp: '1690126924952',
    stepKey: null,
    __typename: 'EngineEvent',
    markerStart: null,
    markerEnd: null,
  },
];
