services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"
      POSTGRES_DB: "test"

  s3:
    image: minio/minio
    container_name: s3
    ports:
      - "4566:4566"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --address :4566
