import {Box, ExternalAnchorButton, NonIdealState, SpinnerWithText} from '@dagster-io/ui-components';

import {AssetMaterializationGraphs} from './AssetMaterializationGraphs';
import {useGroupedEvents} from './groupByPartition';
import {AssetKey} from './types';
import {
  useLatestAssetPartitionMaterializations,
  useRecentAssetEvents,
} from './useRecentAssetEvents';
import {AssetEventHistoryEventTypeSelector} from '../graphql/types';

export const AssetTimeMetadataPlots = ({
  assetKey,
  limit,
  asSidebarSection,
  columnCount,
}: {
  assetKey: AssetKey | undefined;
  limit: number;
  asSidebarSection?: boolean;
  columnCount?: number;
}) => {
  const {events, loading} = useRecentAssetEvents(assetKey, limit, [
    AssetEventHistoryEventTypeSelector.MATERIALIZATION,
    AssetEventHistoryEventTypeSelector.OBSERVATION,
  ]);
  const grouped = useGroupedEvents('time', events, undefined);

  if (loading) {
    return (
      <Box padding={{vertical: 24}} flex={{direction: 'row', justifyContent: 'center'}}>
        <SpinnerWithText label="Loading plots…" />
      </Box>
    );
  }

  return (
    <AssetMaterializationGraphs
      xAxis="time"
      groups={grouped}
      asSidebarSection={asSidebarSection}
      columnCount={columnCount}
      emptyState={
        <Box padding={{horizontal: 24, vertical: 64}}>
          <NonIdealState
            shrinkable
            icon="asset_plot"
            title="Asset plots are automatically generated by metadata"
            description="Include numeric metadata entries in your materializations and observations to see data graphed by time or partition."
            action={
              <ExternalAnchorButton href="https://docs.dagster.io/concepts/metadata-tags/asset-metadata">
                View documentation
              </ExternalAnchorButton>
            }
          />
        </Box>
      }
    />
  );
};

export const AssetPartitionMetadataPlots = ({
  assetKey,
  limit,
  asSidebarSection,
  columnCount,
}: {
  assetKey: AssetKey | undefined;
  limit: number;
  asSidebarSection?: boolean;
  columnCount?: number;
}) => {
  const {materializations, partitionKeys, loading} = useLatestAssetPartitionMaterializations(
    assetKey,
    limit,
  );
  const grouped = useGroupedEvents('partition', materializations, partitionKeys);

  if (loading) {
    return (
      <Box padding={{vertical: 24}} flex={{direction: 'row', justifyContent: 'center'}}>
        <SpinnerWithText label="Loading plots…" />
      </Box>
    );
  }

  return (
    <AssetMaterializationGraphs
      xAxis="partition"
      groups={grouped}
      asSidebarSection={asSidebarSection}
      columnCount={columnCount}
      emptyState={
        <Box padding={{horizontal: 24, vertical: 64}}>
          <NonIdealState
            shrinkable
            icon="asset_plot"
            title="Asset plots are automatically generated by metadata"
            description="Include numeric metadata entries in your materializations and observations to see data graphed by time or partition."
            action={
              <ExternalAnchorButton href="https://docs.dagster.io/concepts/metadata-tags/asset-metadata">
                View documentation
              </ExternalAnchorButton>
            }
          />
        </Box>
      }
    />
  );
};
