# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots['test_build_all_docs 1'] = [
    (
        '.',
        [
            'html',
            'doctrees'
        ],
        [
            '.DS_Store'
        ]
    ),
    (
        './html',
        [
            'intro_tutorial',
            '_sources',
            '_static',
            '_images',
            'apidocs'
        ],
        [
            'principles.html',
            'index.html',
            'searchindex.js',
            'py-modindex.html',
            '.buildinfo',
            'genindex.html',
            'contributing.html',
            'search.html',
            'installation.html',
            'objects.inv'
        ]
    ),
    (
        './html/intro_tutorial',
        [
        ],
        [
            'hello_dag.html',
            'repos.html',
            'pipeline_execution.html',
            'part_ten.html',
            'execution_context.html',
            'actual_dag.html',
            'part_eleven.html',
            'inputs.html',
            'part_twelve.html',
            'configuration_schemas.html',
            'part_thirteen.html',
            'config.html',
            'part_fourteen.html',
            'hello_world.html',
            'part_nine.html'
        ]
    ),
    (
        './html/_sources',
        [
            'intro_tutorial',
            'apidocs'
        ],
        [
            'installation.rst.txt',
            'principles.rst.txt',
            'contributing.rst.txt',
            'index.rst.txt'
        ]
    ),
    (
        './html/_sources/intro_tutorial',
        [
        ],
        [
            'part_eleven.rst.txt',
            'config.rst.txt',
            'execution_context.rst.txt',
            'inputs.rst.txt',
            'pipeline_execution.rst.txt',
            'part_twelve.rst.txt',
            'part_nine.rst.txt',
            'part_ten.rst.txt',
            'hello_world.rst.txt',
            'part_fourteen.rst.txt',
            'part_thirteen.rst.txt',
            'repos.rst.txt',
            'hello_dag.rst.txt',
            'actual_dag.rst.txt',
            'configuration_schemas.rst.txt'
        ]
    ),
    (
        './html/_sources/apidocs',
        [
        ],
        [
            'execution.rst.txt',
            'definitions.rst.txt',
            'utilities.rst.txt',
            'types.rst.txt',
            'decorators.rst.txt',
            'errors.rst.txt'
        ]
    ),
    (
        './html/_static',
        [
        ],
        [
            'plus.png',
            'down-pressed.png',
            'jquery-3.2.1.js',
            'underscore.js',
            'ajax-loader.gif',
            'alabaster.css',
            'documentation_options.js',
            'searchtools.js',
            'up.png',
            'file.png',
            'up-pressed.png',
            'down.png',
            'custom.css',
            'underscore-1.3.1.js',
            'minus.png',
            'comment.png',
            'basic.css',
            'pygments.css',
            'comment-close.png',
            'doctools.js',
            'comment-bright.png',
            'websupport.js',
            'jquery.js'
        ]
    ),
    (
        './html/_images',
        [
        ],
        [
            'inputs_figure_two_untyped_execution.png',
            'hello_dag_figure_one.png',
            'hello_world_figure_two.png',
            'inputs_figure_three_error_modal.png',
            'config_figure_one.png',
            'repos_figure_one.png',
            'inputs_figure_one.png',
            'inputs_figure_four_error_prechecked.png',
            'hello_world_figure_one.png',
            'actual_dag_figure_one.png'
        ]
    ),
    (
        './html/apidocs',
        [
        ],
        [
            'decorators.html',
            'execution.html',
            'utilities.html',
            'definitions.html',
            'types.html',
            'errors.html'
        ]
    ),
    (
        './doctrees',
        [
            'intro_tutorial',
            'apidocs'
        ],
        [
            'installation.doctree',
            'principles.doctree',
            'contributing.doctree',
            'environment.pickle',
            'index.doctree'
        ]
    ),
    (
        './doctrees/intro_tutorial',
        [
        ],
        [
            'part_eleven.doctree',
            'config.doctree',
            'execution_context.doctree',
            'inputs.doctree',
            'pipeline_execution.doctree',
            'part_ten.doctree',
            'part_nine.doctree',
            'part_twelve.doctree',
            'part_fourteen.doctree',
            'hello_world.doctree',
            'part_thirteen.doctree',
            'repos.doctree',
            'configuration_schemas.doctree',
            'actual_dag.doctree',
            'hello_dag.doctree'
        ]
    ),
    (
        './doctrees/apidocs',
        [
        ],
        [
            'execution.doctree',
            'definitions.doctree',
            'types.doctree',
            'utilities.doctree',
            'decorators.doctree',
            'errors.doctree'
        ]
    )
]
