# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots['test_build_all_docs 1'] = [
    (
        [
            '.'
        ],
        [
            'doctrees',
            'html'
        ],
        [
        ]
    ),
    (
        [
            '.',
            'doctrees'
        ],
        [
            'sections'
        ],
        [
        ]
    ),
    (
        [
            '.',
            'doctrees',
            'sections'
        ],
        [
            'api',
            'community',
            'install',
            'learn'
        ],
        [
        ]
    ),
    (
        [
            '.',
            'doctrees',
            'sections',
            'api'
        ],
        [
            'apidocs'
        ],
        [
        ]
    ),
    (
        [
            '.',
            'doctrees',
            'sections',
            'api',
            'apidocs'
        ],
        [
        ],
        [
        ]
    ),
    (
        [
            '.',
            'doctrees',
            'sections',
            'community'
        ],
        [
        ],
        [
        ]
    ),
    (
        [
            '.',
            'doctrees',
            'sections',
            'install'
        ],
        [
        ],
        [
        ]
    ),
    (
        [
            '.',
            'doctrees',
            'sections',
            'learn'
        ],
        [
            'guides',
            'tutorial'
        ],
        [
        ]
    ),
    (
        [
            '.',
            'doctrees',
            'sections',
            'learn',
            'guides'
        ],
        [
        ],
        [
        ]
    ),
    (
        [
            '.',
            'doctrees',
            'sections',
            'learn',
            'tutorial'
        ],
        [
        ],
        [
        ]
    ),
    (
        [
            '.',
            'html'
        ],
        [
            '_images',
            '_modules',
            '_sources',
            '_static',
            'sections'
        ],
        [
            '.buildinfo',
            'genindex.html',
            'index.html',
            'py-modindex.html',
            'search.html'
        ]
    ),
    (
        [
            '.',
            'html',
            '_images'
        ],
        [
        ],
        [
        ]
    ),
    (
        [
            '.',
            'html',
            '_modules'
        ],
        [
            'dagster'
        ],
        [
            'index.html'
        ]
    ),
    (
        [
            '.',
            'html',
            '_sources'
        ],
        [
            'sections'
        ],
        [
            'index.rst.txt'
        ]
    ),
    (
        [
            '.',
            'html',
            '_sources',
            'sections'
        ],
        [
            'api',
            'community',
            'install',
            'learn'
        ],
        [
        ]
    ),
    (
        [
            '.',
            'html',
            '_sources',
            'sections',
            'community'
        ],
        [
        ],
        [
            'code_of_conduct.rst.txt',
            'community.rst.txt',
            'contributing.rst.txt',
            'release_notes.rst.txt'
        ]
    ),
    (
        [
            '.',
            'html',
            '_sources',
            'sections',
            'install'
        ],
        [
        ],
        [
            'install.rst.txt'
        ]
    ),
    (
        [
            '.',
            'html',
            '_sources',
            'sections',
            'learn'
        ],
        [
            'guides',
            'tutorial'
        ],
        [
            'learn.rst.txt',
            'principles.rst.txt'
        ]
    ),
    (
        [
            '.',
            'html',
            '_sources',
            'sections',
            'learn',
            'guides'
        ],
        [
        ],
        [
            '028_to_030_new_concepts.md.txt',
            '028_to_030_upgrade_guide.md.txt'
        ]
    ),
    (
        [
            '.',
            'html',
            '_sources',
            'sections',
            'learn',
            'tutorial'
        ],
        [
        ],
        [
            'actual_dag.rst.txt',
            'config.rst.txt',
            'configuration_schemas.rst.txt',
            'dagstermill.rst.txt',
            'execution_context.rst.txt',
            'expectations.rst.txt',
            'hello_dag.rst.txt',
            'hello_world.rst.txt',
            'index.rst.txt',
            'inputs.rst.txt',
            'multiple_outputs.rst.txt',
            'pipeline_cli_execution.rst.txt',
            'repos.rst.txt',
            'resources.rst.txt',
            'reusable_solids.rst.txt',
            'types.rst.txt',
            'unittesting.rst.txt'
        ]
    ),
    (
        [
            '.',
            'html',
            '_static'
        ],
        [
            'css'
        ],
        [
            'alabaster.css',
            'basic.css',
            'custom.css',
            'doctools.js',
            'documentation_options.js',
            'jquery-3.2.1.js',
            'jquery.js',
            'pygments.css',
            'searchtools.js',
            'underscore-1.3.1.js',
            'underscore.js',
            'websupport.js'
        ]
    ),
    (
        [
            '.',
            'html',
            '_static',
            'css'
        ],
        [
        ],
        [
            'custom.css'
        ]
    ),
    (
        [
            '.',
            'html',
            'sections'
        ],
        [
            'api',
            'community',
            'install',
            'learn'
        ],
        [
        ]
    ),
    (
        [
            '.',
            'html',
            'sections',
            'api'
        ],
        [
            'apidocs'
        ],
        [
            'api.html'
        ]
    ),
    (
        [
            '.',
            'html',
            'sections',
            'api',
            'apidocs'
        ],
        [
        ],
        [
            'errors.html',
            'execution.html',
            'pipeline.html',
            'solids.html',
            'types.html',
            'utilities.html'
        ]
    ),
    (
        [
            '.',
            'html',
            'sections',
            'community'
        ],
        [
        ],
        [
            'code_of_conduct.html',
            'community.html',
            'contributing.html',
            'release_notes.html'
        ]
    ),
    (
        [
            '.',
            'html',
            'sections',
            'install'
        ],
        [
        ],
        [
            'install.html'
        ]
    ),
    (
        [
            '.',
            'html',
            'sections',
            'learn'
        ],
        [
            'guides',
            'tutorial'
        ],
        [
            'learn.html',
            'principles.html'
        ]
    ),
    (
        [
            '.',
            'html',
            'sections',
            'learn',
            'guides'
        ],
        [
        ],
        [
            '028_to_030_new_concepts.html',
            '028_to_030_upgrade_guide.html'
        ]
    ),
    (
        [
            '.',
            'html',
            'sections',
            'learn',
            'tutorial'
        ],
        [
        ],
        [
            'actual_dag.html',
            'config.html',
            'configuration_schemas.html',
            'dagstermill.html',
            'execution_context.html',
            'expectations.html',
            'hello_dag.html',
            'hello_world.html',
            'index.html',
            'inputs.html',
            'multiple_outputs.html',
            'pipeline_cli_execution.html',
            'repos.html',
            'resources.html',
            'reusable_solids.html',
            'types.html',
            'unittesting.html'
        ]
    )
]
