FROM python:3.8-slim

ARG USER_CODE_DEFINITIONS_FILE

COPY ./python_modules/ /tmp/python_modules/

WORKDIR /tmp

RUN pip install \
    -e python_modules/dagster \
    -e python_modules/dagster-pipes \
    -e python_modules/dagster-graphql \
    -e python_modules/libraries/dagster-postgres \
    -e python_modules/libraries/dagster-docker

# Ensure all dagster installs were local
RUN ! (pip list --exclude-editable | grep -e dagster)

WORKDIR /opt/dagster/app

COPY ${USER_CODE_DEFINITIONS_FILE} /opt/dagster/app

# Run dagster gRPC server on port 8090
EXPOSE 8090
