FROM python:3.8-slim

ARG WEBSERVER_VERSION
ARG WEBSERVER_LIBRARY_VERSION

COPY pins.txt pins.txt

RUN pip install \
    -r pins.txt \
    dagster=="${WEBSERVER_VERSION}" \
    dagster-postgres=="${WEBSERVER_LIBRARY_VERSION}" \
    dagster-docker=="${WEBSERVER_LIBRARY_VERSION}" \
    dagster-graphql=="${WEBSERVER_VERSION}" \
    dagster-webserver=="${WEBSERVER_VERSION}"

ENV DAGSTER_HOME=/opt/dagster/dagster_home/
RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
