FROM python:3.8-slim

ARG USER_CODE_VERSION
ARG USER_CODE_LIBRARY_VERSION
ARG USER_CODE_DEFINITIONS_FILE

COPY pins.txt pins.txt

RUN pip install \
    -r pins.txt \
    dagster=="${USER_CODE_VERSION}" \
    dagster-postgres=="${USER_CODE_LIBRARY_VERSION}" \
    dagster-docker=="${USER_CODE_LIBRARY_VERSION}" \
    dagster-graphql=="${USER_CODE_VERSION}"

WORKDIR /opt/dagster/app

COPY ${USER_CODE_DEFINITIONS_FILE} /opt/dagster/app

# Run dagster gRPC server on port 8090
EXPOSE 8090
