DARK_SKY_BASE_URL = 'https://api.darksky.net/forecast'

WEATHER_COLUMNS = [
    'time',
    'summary',
    'icon',
    'sunriseTime',
    'sunsetTime',
    'precipIntensity',
    'precipIntensityMax',
    'precipProbability',
    'precipType',
    'temperatureHigh',
    'temperatureHighTime',
    'temperatureLow',
    'temperatureLowTime',
    'dewPoint',
    'humidity',
    'pressure',
    'windSpeed',
    'windGust',
    'windGustTime',
    'windBearing',
    'cloudCover',
    'uvIndex',
    'uvIndexTime',
    'visibility',
    'ozone',
]

FEATURE_COLUMNS = [
    'sunriseTime',
    'sunsetTime',
    'precipIntensity',
    'precipIntensityMax',
    'precipProbability',
    'temperatureHigh',
    'temperatureHighTime',
    'temperatureLow',
    'temperatureLowTime',
    'dewPoint',
    'humidity',
    'pressure',
    'windSpeed',
    'windGust',
    'windGustTime',
    'windBearing',
    'cloudCover',
    'uvIndex',
    'uvIndexTime',
    'visibility',
    'ozone',
    'summary_Clear throughout the day.',
    'summary_Drizzle in the afternoon and evening.',
    'summary_Drizzle in the morning and afternoon.',
    'summary_Drizzle starting in the afternoon.',
    'summary_Drizzle until morning, starting again in the evening.',
    'summary_Foggy in the morning and afternoon.',
    'summary_Foggy in the morning.',
    'summary_Foggy overnight.',
    'summary_Foggy starting in the afternoon.',
    'summary_Foggy throughout the day.',
    'summary_Foggy until evening.',
    'summary_Heavy rain until morning, starting again in the evening.',
    'summary_Light rain in the afternoon and evening.',
    'summary_Light rain in the evening and overnight.',
    'summary_Light rain in the morning and afternoon.',
    'summary_Light rain in the morning and overnight.',
    'summary_Light rain in the morning.',
    'summary_Light rain overnight.',
    'summary_Light rain starting in the afternoon.',
    'summary_Light rain throughout the day.',
    'summary_Light rain until evening.',
    'summary_Light rain until morning, starting again in the evening.',
    'summary_Mostly cloudy throughout the day.',
    'summary_Overcast throughout the day.',
    'summary_Partly cloudy throughout the day.',
    'summary_Possible drizzle in the afternoon and evening.',
    'summary_Possible drizzle in the evening and overnight.',
    'summary_Possible drizzle in the morning and afternoon.',
    'summary_Possible drizzle in the morning.',
    'summary_Possible drizzle overnight.',
    'summary_Possible drizzle throughout the day.',
    'summary_Possible drizzle until morning, starting again in the evening.',
    'summary_Possible light rain until evening.',
    'summary_Rain in the evening and overnight.',
    'summary_Rain in the morning and afternoon.',
    'summary_Rain in the morning.',
    'summary_Rain overnight.',
    'summary_Rain starting in the afternoon.',
    'summary_Rain throughout the day.',
    'summary_Rain until evening.',
    'summary_Rain until morning, starting again in the evening.',
    'icon_clear-day',
    'icon_cloudy',
    'icon_fog',
    'icon_partly-cloudy-day',
    'icon_rain',
    'didRain_False',
    'didRain_True',
]

LABEL_COLUMN = 'peak_traffic_load'
