DARK_SKY_BASE_URL = 'https://api.darksky.net/forecast'

WEATHER_COLUMNS = [
    'time',
    'summary',
    'icon',
    'sunriseTime',
    'sunsetTime',
    'precipIntensity',
    'precipIntensityMax',
    'precipProbability',
    'precipType',
    'temperatureHigh',
    'temperatureHighTime',
    'temperatureLow',
    'temperatureLowTime',
    'dewPoint',
    'humidity',
    'pressure',
    'windSpeed',
    'windGust',
    'windGustTime',
    'windBearing',
    'cloudCover',
    'uvIndex',
    'uvIndexTime',
    'visibility',
    'ozone',
]

FEATURE_COLUMNS = [
    'sunriseTime',
    'sunsetTime',
    'precipIntensity',
    'precipIntensityMax',
    'precipProbability',
    'temperatureHigh',
    'temperatureHighTime',
    'temperatureLow',
    'temperatureLowTime',
    'dewPoint',
    'humidity',
    'pressure',
    'windSpeed',
    'windGust',
    'windGustTime',
    'windBearing',
    'cloudCover',
    'uvIndex',
    'uvIndexTime',
    'visibility',
    'ozone',
]

LABEL_COLUMN = 'peak_traffic_load'
