import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['intro', 'getting-started/quickstart', 'getting-started/installation', 'getting-started/glossary'],
    },
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      items: ['tutorial/tutorial-etl'],
    },
    {
      type: 'category',
      label: 'Build',
      collapsed: false,
      link: {type: 'doc', id: 'guides/build/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/build'
        }
      ],
    },
    {
      type: 'category',
      label: 'Automate',
      collapsed: false,
      link: {type: 'doc', id: 'guides/automate/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/automate'
        }
      ],
    },
    {
      type: 'category',
      label: 'Monitor',
      collapsed: false,
      link: {type: 'doc', id: 'guides/monitor/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/monitor'
        },
      ],
    },
    {
      type: 'category',
      label: 'Test',
      collapsed: false,
      link: {type: 'doc', id: 'guides/test/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/test'
        }
      ],
    },
    {
      type: 'category',
      label: 'Deploy',
      link: {type: 'doc', id: 'guides/deploy/index'},
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/deploy'
        }
      ],
    },
    {
      type: 'category',
      label: 'About',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'about',
        },
      ],
    },
  ],
  integrations: [
    {
      type: 'category',
      label: 'Categories',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'ETL',
          items: [
            'integrations/airbyte',
            'integrations/sdf',
            'integrations/fivetran',
            'integrations/dlt',
            'integrations/census',
            'integrations/dbt',
            'integrations/dbt-cloud',
            'integrations/sling',
            'integrations/hightouch',
            'integrations/meltano',
          ],
        },
        {
          type: 'category',
          label: 'Storage',
          items: [
            'integrations/snowflake',
            'integrations/gcp/bigquery',
            'integrations/aws/athena',
            'integrations/aws/s3',
            'integrations/duckdb',
            'integrations/deltalake',
            'integrations/aws/redshift',
            'integrations/gcp/gcs',
            'integrations/azure-adls2',
            'integrations/lakefs',
          ],
        },
        {
          type: 'category',
          label: 'Compute',
          items: [
            'integrations/kubernetes',
            'integrations/spark',
            'integrations/aws/glue',
            'integrations/jupyter',
            'integrations/aws/emr',
            'integrations/databricks',
            'integrations/aws/lambda',
            'integrations/docker',
            'integrations/shell',
            'integrations/gcp/dataproc',
          ],
        },
        {
          type: 'category',
          label: 'BI',
          items: ['integrations/looker'],
        },
        {
          type: 'category',
          label: 'Monitoring',
          items: ['integrations/prometheus', 'integrations/datadog', 'integrations/aws/cloudwatch'],
        },
        {
          type: 'category',
          label: 'Alerting',
          items: [
            'integrations/slack',
            'integrations/twilio',
            'integrations/pagerduty',
            'integrations/microsoft-teams',
          ],
        },
        {
          type: 'category',
          label: 'Metadata',
          items: [
            'integrations/secoda',
            'integrations/pandera',
            'integrations/open-metadata',
            'integrations/pandas',
          ],
        },
        {
          type: 'category',
          label: 'Other',
          items: [
            'integrations/cube',
            'integrations/aws/secretsmanager',
            'integrations/openai',
            'integrations/ssh-sftp',
            'integrations/github',
            'integrations/aws/ssm',
            'integrations/aws/ecr',
            'integrations/wandb',
            'integrations/hashicorp',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Community Supported',
      items: [
        'integrations/secoda',
        'integrations/cube',
        'integrations/sdf',
        'integrations/open-metadata',
        'integrations/census',
        'integrations/deltalake',
        'integrations/hightouch',
        'integrations/wandb',
        'integrations/meltano',
        'integrations/hashicorp',
        'integrations/lakefs',
      ],
    },
    {
      type: 'category',
      label: 'All Integrations',
      collapsed: true,
      // link: {type: 'doc', id: 'integrations'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'integrations',
        },
      ],
    },
  ],
  dagsterPlus: [
    'dagster-plus/index',
    'dagster-plus/getting-started',
    {
      type: 'category',
      label: 'Features',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'dagster-plus/features'
        }
      ]
    },
    {
      type: 'category',
      label: 'Deployment',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'dagster-plus/deployment'
        }
      ],
    },
  ],
  api: [
    'api/index',
    'api/api-lifecycle',
    {
      type: 'category',
      label: 'Python API',
      collapsed: false,
      link: {type: 'doc', id: 'api/python-api/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/python-api',
        },
      ],
    }
  ],
};

export default sidebars;
