# This Dockerfile is a containerized Airflow deploy in which the Dagster requirements have been
# installed.

# The filesystem shenanigans and --editable installs below are to support dev, where we want to
# install packages from their local revisions.

# In production, this would simply install from pip, or might use the facilities in a Dockerfile
# like that for puckel/docker-airflow directly, e.g.:

#     docker build --rm \
#       --build-arg PYTHON_DEPS="dagster dagster-graphql dagster-airflow dagster-aws dagster-cron" \
#       -t puckel/docker-airflow .

# To run the Airflow UI, bind-mounting your local DAGs, run:

#     docker run -d -p 8080:8080 \
#       -v $AIRFLOW_HOME/dags:/usr/local/airflow/dags dagster-airflow-webserver webserver

FROM puckel/docker-airflow

USER root

ADD dagster dagster
ADD dagster-graphql dagster-graphql
ADD dagster-aws dagster-aws
ADD dagster-cron dagster-cron
ADD dagster-gcp dagster-gcp
ADD dagster-airflow dagster-airflow
ADD examples examples

RUN pip install --no-deps -e dagster -e dagster-graphql -e dagster-aws -e dagster-cron -e dagster-gcp -e dagster-airflow -e examples
RUN pip install -e dagster -e dagster-graphql -e dagster-aws -e dagster-cron -e dagster-gcp -e dagster-airflow -e examples

USER airflow
