[tox]
requires =
    tox-uv>=1.16
skipsdist = true

[testenv]
runner = uv-venv-lock-runner
uv_sync_locked = false
uv_sync_flags = --frozen
download = True
passenv =
    CI_*
    AWS_SECRET_ACCESS_KEY
    AWS_ACCESS_KEY_ID
    BUILDKITE*
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
setenv =
    STRICT_GRPC_SERVER_PROCESS_WAIT = "1"
    COREPACK_ENABLE_DOWNLOAD_PROMPT = "0"
dependency_groups =
    test
allowlist_externals =
  /bin/bash
  corepack
  git
  yarn
  uv
commands =
  corepack enable
  !windows: /bin/bash -c '! uv pip list --exclude-editable | grep -e dagster'
    yarn install
  yarn tsgo
  yarn lint:ci
  yarn jest --clearCache
  yarn jest-all-silent --testTimeout=10000 --ci --logHeapUsage --workerIdleMemoryLimit=1GB
  git diff --exit-code
