install:
	pip3 install -e check
	pip3 install -e solidic 
	pip3 install -e solidic-pandas 
	pip3 install -e dagster 
.PHONY: install

develop:
	pip3 install pylint
	pip3 install yapf 
	pip3 install rope 
.PHONY: install
