[tox]
requires =
    tox-uv>=1.16
envlist = py{39,38,37,36}-{unix,windows}
skipsdist = true

[testenv]
runner = uv-venv-lock-runner
uv_sync_locked = false
uv_sync_flags = --frozen
download = True
passenv =
    CI_*
    BUILDKITE*
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
setenv =
  STRICT_GRPC_SERVER_PROCESS_WAIT = "1"
extras =
    notebook
dependency_groups =
    test

allowlist_externals =
  /bin/bash
  uv
commands =
  !windows: /bin/bash -c '! uv pip list --exclude-editable | grep -e dagster -e dagit'
  pytest -v --junitxml=dagit_test_results.xml {posargs}
