[tox]
requires =
    tox-uv>=1.16
envlist = py{39,38,37}-{unix,windows}
skipsdist = true

[testenv]
runner = uv-venv-lock-runner
uv_sync_locked = false
uv_sync_flags = --frozen
download = True
passenv =
    CI_*
    AZURE_*
    BUILDKITE*
    SSH_*
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
extras =
    pandas
dependency_groups =
    test
allowlist_externals =
  /bin/bash
  uv
commands =
  !windows: /bin/bash -c '! uv pip list --exclude-editable | grep -e dagster -e dagit'
  pytest -vv {posargs}
