[tox]
requires =
    tox-uv>=1.16
skipsdist = true

[testenv]
runner = uv-venv-lock-runner
uv_sync_locked = false
uv_sync_flags = --frozen
download = True
passenv =
    CI_*
    BUILDKITE*
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
    # TODO add additional env var requirements and add them to .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
dependency_groups =
    test
allowlist_externals =
  /bin/bash
  uv
commands =
  !windows: /bin/bash -c '! uv pip list --exclude-editable | grep -e dagster -e dagit'
  pytest -vv ./dagster_omni_tests --durations 10 {posargs}