[tox]
requires =
    tox-uv>=1
skipsdist = true

[testenv]
download = True
passenv =
    CI_*
    BUILDKITE*
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
deps =
  -e .[test]
allowlist_externals =
  /bin/bash
  uv
commands =
  !windows: /bin/bash -c '! uv pip list --exclude-editable | grep -e dagster -e dagit'
  pytest -vv ./dagster_shared_tests {posargs}
