[tox]
requires =
    tox-uv>=1.16
envlist = {default,old_kubernetes,nightly}
skipsdist = true

[testenv]
runner = uv-venv-lock-runner
uv_sync_locked = false
uv_sync_flags = --frozen
download = True
passenv =
    HOME
    AWS_*
    BUILDKITE*
    CI_*
    DAGSTER_*
    DOCKER_*
    GOOGLE_*
    KUBECONFIG
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
dependency_groups =
    test
    old_kubernetes: test-old-kubernetes
allowlist_externals =
  /bin/bash
  uv
commands =
  !windows: /bin/bash -c '! uv pip list --exclude-editable | grep -e dagster'
  !nightly: pytest --log-cli-level=INFO -m 'not nightly' -vv {posargs}
  nightly: pytest --log-cli-level=INFO -m 'nightly' -vv {posargs}
