"""Constants used across Dagster assets and resources."""

DEFAULT_HACKER_NEWS_LIMIT = 100
DEFAULT_HACKER_NEWS_PAGE_SIZE = 50
DEFAULT_HACKER_NEWS_MAX_PAGES = 10
DEFAULT_HACKER_NEWS_MAX_STORIES = 100  # Default number of stories to fetch from API

DEFAULT_SCRAPE_BATCH_SIZE = 50
DEFAULT_SCRAPE_TIMEOUT = 10
DEFAULT_MAX_CONTENT_LENGTH = 100000

MAX_HEADLINE_LENGTH = 1000
MAX_CONTENT_LENGTH = 100000

DEFAULT_SCHEMA = "PUBLIC"
