import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'intro',
        'getting-started/quickstart',
        'getting-started/installation',
        'getting-started/glossary',
        'getting-started/concepts',
      ],
    },
    {
      type: 'category',
      label: 'ETL pipeline tutorial',
      collapsed: false,
      link: {type: 'doc', id: 'etl-pipeline-tutorial/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'etl-pipeline-tutorial',
        },
      ],
    },
    {
      type: 'category',
      label: 'Build',
      collapsed: false,
      link: {type: 'doc', id: 'guides/build/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/build',
        },
      ],
    },
    {
      type: 'category',
      label: 'Automate',
      collapsed: false,
      link: {type: 'doc', id: 'guides/automate/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/automate',
        },
      ],
    },
    {
      type: 'category',
      label: 'Operate',
      collapsed: false,
      link: {type: 'doc', id: 'guides/operate/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/operate',
        },
      ],
    },
    {
      type: 'category',
      label: 'Monitor & debug',
      collapsed: false,
      link: {type: 'doc', id: 'guides/monitor/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/monitor',
        },
      ],
    },
    {
      type: 'category',
      label: 'Test',
      collapsed: false,
      link: {type: 'doc', id: 'guides/test/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/test',
        },
      ],
    },
    {
      type: 'category',
      label: 'Deploy',
      link: {type: 'doc', id: 'guides/deploy/index'},
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/deploy',
        },
      ],
    },
    {
      type: 'category',
      label: 'Migrate',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/migrate',
        },
      ],
    },
    {
      type: 'category',
      label: 'Labs',
      link: {type: 'doc', id: 'guides/labs/index'},
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/labs',
        },
      ],
    },
    {
      type: 'category',
      label: 'About',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'about',
        },
      ],
    },
  ],
  examples: [
    {
      type: 'category',
      label: 'Examples',
      collapsed: false,
      link: {type: 'doc', id: 'examples/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
      ],
    },
  ],
  integrations: [
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: ['integrations/guides/multi-asset-integration'],
    },
    {
      type: 'category',
      label: 'Libraries',
      collapsible: false,
      link: {type: 'doc', id: 'integrations/libraries/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'integrations/libraries',
        },
      ],
    },
  ],
  dagsterPlus: [
    'dagster-plus/index',
    'dagster-plus/getting-started',
    {
      type: 'category',
      label: 'Features',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'dagster-plus/features',
        },
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'dagster-plus/deployment',
        },
      ],
    },
  ],
  api: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      items: [
        'api/index',
        {
          type: 'autogenerated',
          dirName: 'api/api-lifecycle',
        },
      ],
    },
    {
      type: 'category',
      label: 'Dagster core',
      collapsed: false,
      link: {type: 'doc', id: 'api/dagster/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/dagster',
        },
      ],
    },
    {
      type: 'category',
      label: 'Dagster libraries',
      collapsed: false,
      link: {type: 'doc', id: 'api/libraries/index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/libraries',
        },
      ],
    },
  ],
};

export default sidebars;
