[tox]
requires =
    tox-uv>=1.16
skipsdist = true
envlist = py311

[testenv]
runner = uv-venv-lock-runner
uv_sync_locked = false
uv_sync_flags = --frozen
download = True
passenv =
    CI_*
    AWS_SECRET_ACCESS_KEY
    AWS_ACCESS_KEY_ID
    BUILDKITE*
    LC_ALL
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
dependency_groups =
    test
allowlist_externals =
  /bin/bash
  /usr/bin/env
  uv
  sphinx-build

[testenv:sphinx-mdx-local]
basepython = python3.11
# Since M3 Macs and Windows systems cannot parallelize the build,
# do not set -j flag
commands =
  !windows: /usr/bin/env bash -c '! uv pip list --exclude-editable | grep -e dagster | grep -v dagster-iceberg | grep -v dagster-polars'
  sphinx-build -M clean sphinx sphinx/_build
  sphinx-build -M mdx sphinx sphinx/_build -W

[testenv:sphinx-mdx-vercel]
basepython = python3.11
# -j auto distributes the build over N parallel processes
# If auto argument is given, Sphinx uses the number of CPUs as N
# https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-j
commands =
  sphinx-build -M clean sphinx sphinx/_build
  sphinx-build -M mdx sphinx sphinx/_build -W -j auto
