# Example commands

list:
	dagster pipeline list
.PHONY: list

print_hello:
	dagster pipeline print pandas_hello_world
.PHONY: print_hello

execute_hello:
	dagster pipeline execute pandas_hello_world -e pandas_hello_world/env.yml
.PHONY: execute_hello
