[tox]
skipsdist = true

[testenv]
download = True
passenv =
    CI_*
    BUILDKITE*
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
install_command = uv pip install {opts} {packages}
deps =
  -e ../../dagster[test]
  -e ../../dagster-pipes
  -e ../dagster-shared
  -e ../dagster-managed-elements
  -e ../create-dagster
  -e ../dagster-dg-cli
  -e ../dagster-dg-core[test]
  -e ../dagster-cloud-cli
  -e ../dagster-rest-resources
  -e ../../dagster-graphql
  -e .[test]
allowlist_externals =
  /bin/bash
  uv
commands =
  !windows: /bin/bash -c '! pip list --exclude-editable | grep -e dagster'
  pytest -vv {posargs}
