[tox]
requires =
    tox-uv>=1
skipsdist = true

[testenv]
download = True
passenv =
    CI_*
    BUILDKITE*
    PYTEST_ADDOPTS
    PYTEST_PLUGINS
    # TODO add additional env var requirements and add them to .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py

deps =
  pytest
  pytest-xdist
  typer
  -e ../dagster-dg-core[test]
  -e ../../../python_modules/dagster[test]
  -e ../../../python_modules/dagster-test
  -e ../../../python_modules/dagster-graphql
  -e ../../../python_modules/dagster-pipes
  -e ../../../python_modules/libraries/dagster-shared
  -e ../../../python_modules/libraries/dagster-cloud-cli
  -e ../../../python_modules/libraries/dagster-rest-resources
  -e ../../../python_modules/libraries/create-dagster
  -e ../../../python_modules/automation
  -e ../dagster-dbt
  -e ../dagster-fivetran
  -e ../dagster-sling
  plus: -e ../../../python_modules/libraries/dagster-aws
  plus: -e ../../../python_modules/libraries/dagster-k8s
  plus: -e ../../../python_modules/libraries/dagster-docker
  -e .[ai]
allowlist_externals =
  /bin/bash
  uv
  jsonschema
  npm
commands =
  !windows: /bin/bash -c '! uv pip list --exclude-editable | grep -e dagster -e dagit'
  plus: npm install -g @action-validator/core @action-validator/cli --save-dev
  plus: pytest ./dagster_dg_cli_tests/cli_tests/plus_tests -vv --durations 10 {posargs}
  general: pytest ./dagster_dg_cli_tests -vv --durations 10 -n 4 --dist worksteal {posargs} -m "not slow and not serial" --ignore=./dagster_dg_cli_tests/cli_tests/plus_tests
  slow: pytest ./dagster_dg_cli_tests -vv --durations 10 -n 4 --dist worksteal {posargs} -m "slow and not serial" --ignore=./dagster_dg_cli_tests/cli_tests/plus_tests
  serial: pytest ./dagster_dg_cli_tests -vv --durations 10 {posargs} -m "serial" --ignore=./dagster_dg_cli_tests/cli_tests/plus_tests
